### ISSUE TITLE
FR: Allow templates and filter for "list today's google events"

### ISSUE THREAD

**Issue by brimwats** [YukiGasai/obsidian-google-calendar#10]
Thank you for all the work on this! it's great. I would like to insert events in a list from one calendar only in a bullet point style, not a table.

**Comment by YukiGasai** [comment]
Sound like a good idea. Should the selection be in a popup?

**Comment by brimwats** [comment]
good question 🤔 a pop-up would be pretty great if possible, otherwise it could just paste in what it currently does in a bullet list

**Comment by YukiGasai** [comment]
I added the popup with the last commit, please check out the latest version. The command is renamed to insert event.

You can now:
- change the date
- switch between bullet list and table
- deselect calendars to ignore
- deselect events to ignore
- define the table header
- save settings as template
- load templates
- remove templates in the settings

**Comment by brimwats** [comment]
I tried the latest commit and it works wonderfully! thank you!!

**Comment by YukiGasai** [comment]
Thank you for the idea 😊
