### ISSUE TITLE
Login button not working for Oauth in ios and android

### ISSUE THREAD

**Issue by ryukegit** [YukiGasai/obsidian-google-calendar#102]
Login button not working for Oauth in ios and android

**Comment by YukiGasai** [comment]
Hi @ryukegit,
I tested the plugin on version 1.9.3 and was able to Login. Please make sure the custom client option is on, and you use the Refresh token from the same client.

**Comment by ryukegit** [comment]
Yes custom client is on
But unable to press login button

**Comment by YukiGasai** [comment]
Yea the button is pressed, but there is no feedback at the moment (will be fixed ^^), if you have entered a valid client id, client secret and Refresh token you should login, please try and restart the app as well.

**Comment by ryukegit** [comment]
Already tried but not working

**Comment by YukiGasai** [comment]
Please make sure there are no spaces at the end of the strings.

What version of the plugin are you using?

**Comment by ryukegit** [comment]
Latest version
Sure there are no spaces at the end
Tried on both ipad pro and samsung note 20 ultra
Button is non responsive

**Comment by YukiGasai** [comment]
I tested again and can't reproduce this.
It would be very helpful if you could debug this with a pc.

- Enable USB debugging in dev Settings on phone.
- Connect Samsung phone to pc.
- on pc, open chrome at `chrome://inspect/#devices`
- press inspect

Check the dev console for any errors.

**Comment by ryukegit** [comment]
Sorry but I only have android phone and an ipad

**Comment by ryukegit** [comment]
Uploading Screen_Recording_20230402_210720_Obsidian.mp4…

**Comment by ryukegit** [comment]
/

**Comment by ryukegit** [comment]
https://share-me.video/video/bCeSChF2XwqxCsGN77igDAMXnCaflL038nPbcijQqshCIggPamdxiFv7Ta5OBWqp

Here is screen recording

**Comment by YukiGasai** [comment]
Now I understand. You are required to already have a working refresh token. You get the token from a Pc where the plugin is installed.

I understand that you don't have a pc. I will try to create a workaround, but this can take longer. The best option would be using a pc.

**Comment by ryukegit** [comment]
Thankyou for your support

**Comment by YukiGasai** [comment]
Hi,
I updated the plugin, so you should be able to login without pc now. 
You will have to update your Google cloud project for that [guide](https://github.com/YukiGasai/obsidian-google-calendar/blob/ffc9e77f39943f334a2dae0b2f9283a54faaf2e6/README.md?plain=1#L30-L44).

The problem with the mobile app is, that no local server can be started. A publicly hosted server will replace this now. The source code of this server can be found [here](https://github.com/YukiGasai/GoogleAuthObsidianRedirect). Its only job is to redirect the callback for the Google authentication to the obsidian URI.

**Comment by YukiGasai** [comment]
Please try again, you answered so fast that the build was not finished on the server.

**Comment by ryukegit** [comment]
Working like a charm thank you for creating this plugin😁
