### ISSUE TITLE
[FR] time range for timeline and weekly review

### ISSUE THREAD

**Issue by caasion** [YukiGasai/obsidian-google-calendar#104]
Hi,

I am glad that my appearance pull request was merged as an updated. I am happy to contribute to such a useful plugin!

**Rationale:** Most events in my calendar span across morning to night, but I don't find much use for times in midnight, so it isn't needed for times like 0 midnight - 5 am to show up. It only takes up vertical space in my sidebar.

**Request**: I would like the time range of timeline and weekly view customizable (either through settings or a pop-up/drop down menu from the timeline view and weekly view itself).

Please consider this request. Thank you!

**Comment by YukiGasai** [comment]
Ohh, 
before the pull request merge the `hourRange` achieved that.
See #53 for more info.

![image](https://user-images.githubusercontent.com/38146192/229312362-b026dc50-7d14-4e99-9ac5-02951bc3a04d.png)

**Comment by YukiGasai** [comment]
I fixed the option for the timline view, but it will not work in the week view or if the `navigation` option is set.

**Comment by caasion** [comment]
is it possible to have hourRange for the timeline view? (when it isn't in a code block)

**Comment by YukiGasai** [comment]
No, but only because I could find out how to configure this properly.

It would be great to have the option to configure views on a view basis, like code blocks.

**Comment by caasion** [comment]
One possibility is to have a settings button at the top right of each view where you can change settings of the view. The options would be specific to the views and the settings would be consistent for that view (even if you open it anywhere else)

**Comment by YukiGasai** [comment]
Hi @caasion, 
you can now right-click the tab of the view to show a settings page.
![image](https://user-images.githubusercontent.com/38146192/230683226-bb29721f-0208-45d1-b41d-9634bcae8c36.png)
I had to change a lot of stuff, if any problems occur just report them here.

**Comment by caasion** [comment]
it's impressive that you implemented this so quickly!

a few things I've noticed:

- full day events disappear when you set the hour range to higher than 1
  - a new section for full day events might be needed
- the timeline gets really wonky when min of hour range is >1 and max of hour range is >24
  - you could prevent that by making a double slider instead (one for min and the other for max)
  - [This](https://svelte.dev/repl/e93d43c42b434e3aa3e2a5815f805c75?version=3.22.3) seems to be a pretty good svelte slider than you can use (idk how to implement it myself without messing other things up)
- you could merge the "include" and "exclude" options because if you are including something, it automatically excludes something
  - you could give an option to either "include" or "exclude" and then choose the calendar afterwards  
- the cssclasses are not consistent with the obsidian ones (obsidian css doesn't use camelCase, but dash-case)
  - if you don't mind, i could fix this part (along with adding theme css variables to the views)
- I can't find the option to change the date display of schedule view
  - also i messed up with one part of the css in schedule view
    - if you can find it, in `.gcal-schedule-date-display`, please remove `flex: 0 0 100px;`
- it would be nice to add a "hide settings" button direclty in the settings menu so we don't have to right click the tab to close it again
- with the new right click menu, we've lost the option to `close all`, `close others`, `split right` etc., it's not the most important, but it would be nice if they came back

i appreciate all the work you've put in for my feature request! thank you for considering it in the first place.

**Comment by YukiGasai** [comment]
- Added exit button
- Added slider for timespan, hourRange
- Added DayOffset
- Removed `.gcal-schedule-date-display` -> `flex: 0 0 100px;`
- Added logic so exlude or include is shown after first selection

I tried to add the default menu options back, but didn't get it to work.
