### ISSUE TITLE
failure in first `googleListCalendars()` call will cause subsequent calls to break

### ISSUE THREAD

**Issue by CovetingEpiphany2152** [YukiGasai/obsidian-google-calendar#105]
Hi Yuki,

If this line throws an error:
https://github.com/YukiGasai/obsidian-google-calendar/blob/master/src/googleApi/GoogleListCalendars.ts#L51 

It will cause this line to not run:
https://github.com/YukiGasai/obsidian-google-calendar/blob/master/src/googleApi/GoogleListCalendars.ts#L57

And therefore, lock will always be true. And subsequent calls to `googleListCalendars()` will always return empty list.

This can be reproduced by starting Obsidian without an internet connection and calling the getCalendars API. Then, even if the internet is back up after that, subsequent calls will return an empty array.

![image](https://user-images.githubusercontent.com/7296340/229522971-c921eb6d-e11b-431d-aeeb-1eff72c60bc5.png)

I was thinking of pushing a pull request to set the lock to false in the event of any exception thrown in line 57, and throwing the exception again after that. However, I'm not sure why this lock is created in the first place. JS is single-threaded, so wouldn't there be no need for this lock at all?

If I understand this correctly, you are likely trying to prevent another immediate `googleListCalendars()` call from sending another request while the previous one is still unresolved (and therefore `cachedCalendars`) is not updated yet. However, by doing this, your second `googleListCalendars()` would return an empty array, which is not ideal. I think it would make more sense to remove this "lock" entirely. If there are multiple `googleListCalendars()` calls, so be it. Only the first few will send requests, and once `cachedCalendars` is updated, the cache will come into play and no requests will be sent anymore.

Thoughts?

**Comment by YukiGasai** [comment]
Hi, thank you for pointing this out.
I tried to implement better exception for #90.

You have understood my intention with the lock completely right ^^. I tried to save some requests, but I think there was a problem with caching as well.

**Comment by CovetingEpiphany2152** [comment]
I believe this is fixed in 
https://github.com/YukiGasai/obsidian-google-calendar/commit/1299a3beb9f978f946421a077ca5c6eaffaad3ed
