### ISSUE TITLE
Plugin layout is really off

### ISSUE THREAD

**Issue by jackli89** [YukiGasai/obsidian-google-calendar#11]
This plugin is so useful but I've tested it with Minimal theme and the Default and the spacing and layout is all off. Is there a way to modify this in CSS?

**Comment by YukiGasai** [comment]
Sure, but can you give a concrete example. I use minimal theme too and didn't notice anything.

**Comment by jackli89** [comment]
Sorry should've been more clear. The schedule view is off not the plugin in general. 
![CleanShot 2022-09-26 at 09 41 39@2x](https://user-images.githubusercontent.com/100640704/192334314-393aedfb-7359-4591-920b-e4746f31f92e.png)

Also, I'm noticing when it adds events to a table into a note it brings in all the details such as meeting links and that messes up the table as well. Is there a way to only bring in start-end time and title of event? 

Thank you!

**Comment by YukiGasai** [comment]
I'm currently making changes to the insert command, check out #11 for this.

**Comment by YukiGasai** [comment]
If the problem is still occurring, please reopen the issue.
