### ISSUE TITLE
In Note block empty even after re login

### ISSUE THREAD

**Issue by Rikubyakko** [YukiGasai/obsidian-google-calendar#111]
Hey, after more than a week of Obsidian Google Calendar working well, everything stopped working when i opened obsidian today.
I had LOADING on my gCal pannels and my in note gEvent blocks were empty.
I remembered someone said he encountered auth issue so i logged out and re logged and my pannel went back to normal, but all my in note gEvent remains empty. 

![image](https://user-images.githubusercontent.com/86108325/231202965-8b10cdcf-88e9-4f53-bc8d-f17fe0ec12b3.png)

**Comment by Rikubyakko** [comment]
Thank you for this fast answer !
It's AnuPpuccin theme, really customizable :)

Here is the code for the timeline view of the screenshot :

> [!today]+ ‎‎ Planning
>> [!multi-column]
>>> [!yesterday|min-0|align-left] ‎ Hier
>>> ```gEvent
>>> date: yesterday
>>> type: day
>>> hourRange: [7, 24]
>>> ```
>>> 
>> 
>>> [!today|min-0|align-center] ‎ Aujourd'hui
>>> ```gEvent
>>> date: today
>>> type: day
>>> hourRange: [7, 24]
>>> ```
>>> 
>> 
>>> [!tomorrow|min-0|align-right] ‎ Demain
>>> ```gEvent
>>> date: tomorrow
>>> type: day
>>> hourRange: [7, 24]
>>> ```

(it worked well until today)

And here is another block that also worked before :

> [!today]+ # Planning
> ```gEvent
> type: [schedule]
> date: today
> timespan: 0
> ```

![image](https://user-images.githubusercontent.com/86108325/231227915-245d9c2e-0dd9-4583-a99e-b14512dcdd9a.png)
![image](https://user-images.githubusercontent.com/86108325/231227980-a3dea4e9-bc8a-4c3b-a28b-8b934120718b.png)

**Comment by Rikubyakko** [comment]
Thank you for the quick support, and for this useful plugin !

**Comment by Rikubyakko** [comment]
Nice improvement thanks, will be useful for my weekly notes !

Sadly it seems like only my timeline blocks are back :

![image](https://user-images.githubusercontent.com/86108325/231529292-1365b934-e2d4-4fa0-9f20-abb800b6d22b.png)

My schedules are still empty :

![image](https://user-images.githubusercontent.com/86108325/231529542-1fbc0a9e-0cb6-428b-bfde-732064c65a91.png)

![image](https://user-images.githubusercontent.com/86108325/231529622-6f405820-6c5f-40d1-b583-3e3f070fcbae.png)

**Comment by YukiGasai** [comment]
@Rikubyakko
Please set the timespan to 1.

**Comment by Rikubyakko** [comment]
It worked thanks !

Thank you :)
