### ISSUE TITLE
Google Login Error

### ISSUE THREAD

**Issue by MoreMoss** [YukiGasai/obsidian-google-calendar#112]
![image](https://user-images.githubusercontent.com/130698586/231854460-5175ba7d-dbc5-49c3-b951-7dad88979ab1.png)

Cannot change settings for less secure apps in google account settings either. Any ideas?

**Comment by YukiGasai** [comment]
Are you using your own client?

**Comment by PedroReyes** [comment]
Hello @YukiGasai ,

Same problem here. It happens when you try to log with your own account using this setup and you press in the email at the browser tab:

![image](https://user-images.githubusercontent.com/4096108/232057472-a1692e43-8f90-432c-8307-849e173b6f70.png)

Best regards,
Pedro Reyes.

**Comment by PedroReyes** [comment]
Hello @YukiGasai ,

Then it is me the one that is confused, sorry.

The "block page" appears to me when I try to log with my google account.

Maybe I am a bit lost. Shall I make a video?

The steps are:

1. Click on login (using the screenshot)
2. Click on my google account in the browser
3. Block page screenshot shows up

According to what you say I should use Google Developer Console. I will give it a try ✌ a bit more complicated however for an average user I think.

Thanks for the plugin @YukiGasai .

Best regards,
Pedro Reyes.

**Comment by YukiGasai** [comment]
You have to enable the first setting. Use your own client and follow the instructions in the readme to create a own client with your own client id and client secret. After entering them in the settings you can press the login button.
