### ISSUE TITLE
Phone log in issue

### ISSUE THREAD

**Issue by Rikubyakko** [YukiGasai/obsidian-google-calendar#114]
Hey,

Using a remote vault synced on PC and phone, and always getting connection eror message for google calendar plugin.

But whenever i press log in in the plugin settings i end up on this page : 

![Screenshot_2023-04-18-15-17-34-255_com opera gx](https://user-images.githubusercontent.com/86108325/232824279-dba9a1f8-c79b-49f5-adb8-408ed9710282.jpg)

(Request from this application is not valid)

**Comment by YukiGasai** [comment]
Have you added the `https://google-auth-obsidian-redirect.vercel.app` as JavaScript origin and `https://google-auth-obsidian-redirect.vercel.app/callback` as redirect like described in the readme?
