### ISSUE TITLE
Month view

### ISSUE THREAD

**Issue by SVANNER** [YukiGasai/obsidian-google-calendar#115]
The buttonarrows to go next/previous month is not changing the month.

![image](https://user-images.githubusercontent.com/3523354/233549917-ad0f87e7-1bbc-4830-bde8-c8d6517f4332.png)

 I am using:

Obsidian : 1.1.16
Google Calendar: 1.9.10

**Comment by YukiGasai** [comment]
Hi, thank you for reporting this.
It should be fixed with the latest version.

**Comment by YukiGasai** [comment]
Hi,
this sounds good. 
The month view is using the obsidian calendar ui package. 
It is intended that the today button doesn't appear for the android view.

If there are no other problems, you can close this issue.

**Comment by SVANNER** [comment]
Thanks for the info !
