### ISSUE TITLE
Followed all directions  web view stuck at google login page

### ISSUE THREAD

**Issue by Free-Radical** [YukiGasai/obsidian-google-calendar#116]
See image attached, other google plugin for tasks is working fine.

google auth reports : 
'''Authentication successful! Please return to obsidian.'''

but when calendar starts ini Obsidian  the following "webview" comes up and **doesn't allow clicking etc to login**

![Screenshot_20230423_162829](https://user-images.githubusercontent.com/753154/233867417-2cf96c66-a820-419e-afcf-ea3bbe6062a8.png)

**Comment by YukiGasai** [comment]
Hi, 
the plugin login process is used for everything except the web view.
The web view is just a frame that displays the Google calendar webpage. You should be automatically redirected to a login page when opening the webview.
![image](https://user-images.githubusercontent.com/38146192/234021547-75bd7e99-81a5-41cf-ae15-9d35949c1466.png)

What OS are you using, what version of obsidian and what version of the plugin?

**Comment by Free-Radical** [comment]
ok, still not going to "google login" page. I'm wondering if its a Firefox/Linux change (Firefox 112..0.1)

also see error:
`Could not list Google calendar` , etc



Obsidian 1.1.16
Goog Cal 1.9.11

Operating System: Kubuntu 23.04
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.0-20-generic (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 31.2 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1080/PCIe/SSE2

**Comment by BananenRitter** [comment]
Same problem. Obsidian opens web view, it does register my mouse input but not all UI elements do something when i click them. Therefore i cant log in manually. I tested Firefox and Edge and set both to default browser. Then i restarted Obsidian my pc woth no difference. The UI doesnt even look different when i have another browser as default.

Obsidian 1.1.16
MS Edge Version 110.0.1587.41 (Offizielles Build) (64-Bit)
Firefox 112.0.1 (64-Bit)
Win 10 Version 19045.2846

![gCal web view login issue](https://user-images.githubusercontent.com/100603352/234347444-b28ed7e5-37c8-40e0-aa09-506c76f6a9c1.png)

**Comment by YukiGasai** [comment]
Thank you for reporting this,
I was able to reproduce this issue on another pc as well.

**Comment by BananenRitter** [comment]
I found a solution. Not a good one though. I was able to enter different windows with spamming clicking on something which lead me to the sign up page, then i went to log in, then i tried to klick on google apps which doesnt do anything but i thought maybe if i close and reopen the web view it works and it did work.

Is there a way to see one week in google calender?

Is there a way to get the widgets inside the main tab?

The setup for the OAuth client was difficutl to understand because there are no screenshots and neither do you know where to click to find the options. Maybe you want to make a step by step guide otherwise people might be repelled my so many things to do manually

**Comment by YukiGasai** [comment]
With the latest update, I added a login button in the settings box. 
![image](https://user-images.githubusercontent.com/38146192/234408592-064559d3-be87-48dd-9fec-7897d93bb5fa.png)
The button will redirect you to the login page. After you're logged in, you can refresh the view to get back to the calendar.
To open the view settings right click the Tab of the view.
![image](https://user-images.githubusercontent.com/38146192/234408786-515ce112-4a12-4551-9d59-13a3bca58df4.png)
