### ISSUE TITLE
problem with Auto create Event Notes

### ISSUE THREAD

**Issue by khsunny87** [YukiGasai/obsidian-google-calendar#117]
whenever I run the obsidian, automatically creates event notes.

but in that case, the notes are not applied to the templates.

the notes only had their name and event-id frontmatter.
that's all.

plz, fix it.

**Comment by YukiGasai** [comment]
Hi, 
what template plugin are you using and could you share your template so I can reproduce your setup?

**Comment by khsunny87** [comment]
'GoogleCalendar.md' is my template
and the other one is auto-created note.

in fact, it works well when i operate gCal Trigger Auto import on command
palette,
but auto-creation, which runs at starting obsidian, always failed to follow
the template and it just gives the note with title and event-id in the
frontmatter.


2023년 4월 26일 (수) 오전 12:36, YukiGasai ***@***.***>님이 작성:

**Comment by khsunny87** [comment]
I think there is something wrong with loading a template at the beginning
of obsidian.

2023년 4월 26일 (수) 오전 11:43, khsunny87 ***@***.***>님이 작성:

**Comment by khsunny87** [comment]
I tried using a new vault and only installed two plugins, Tempalter and Google Calendar, 
but I'm still experiencing the same problem. 

The plugin works properly after the command "gCal Trigger Auto import", 
but they always fail to apply the template at startup.

I suspect that the problem lies in the "AutoEventNoteCreator.ts" source code. 
Specifically, the line "if ((!plugin.coreTemplatePlugin && !plugin.templaterPlugin) || !templateName)" could be causing the issue. It appears to be related to plugin loading.

**Comment by YukiGasai** [comment]
Hi,
I was able to reproduce this and updated the plugin.
Thank you for your debugging work. 
The final problem was that I moved the function call to run the initial check before defining the templater plugin. This caused the `if ((!plugin.coreTemplatePlugin && !plugin.templaterPlugin) || !templateName)` to be false.

Please check yourself if everything works as expected now.
If all is fine, you can close this issue.
