### ISSUE TITLE
Google schedule view is broken

### ISSUE THREAD

**Issue by tecnoborder** [YukiGasai/obsidian-google-calendar#119]
I have been experiencing this issue for the past couple of weeks or so. The timeline view no longer works. I got an empty tab in the sidebar

**Comment by YukiGasai** [comment]
I can't reproduce this. Can you see the timeline view in the codeblock
~~~
```gEvent
type: day
date: 2023-05-06
```
~~~

**Comment by tecnoborder** [comment]
sorry I mean the schedule view. When I open it I see an empty tab in the sidebar
<img width="297" alt="Screenshot 2023-05-07 at 14 56 50" src="https://user-images.githubusercontent.com/18950662/236678969-ba50dd31-9753-499c-9be2-dc29e2fabeae.png">

**Comment by YukiGasai** [comment]
Can you check if the timeline (view / codeblock) displays your events?
If not, try logging out and back in.

**Comment by tecnoborder** [comment]
Now it works, I logged it again. Thanks a lot for the support
