### ISSUE TITLE
Auto resize views instead of fixed sizes

### ISSUE THREAD

**Issue by AngelusDomini** [YukiGasai/obsidian-google-calendar#12]
Hey, @YukiGasai. Love the work that you've done with this plugin! But I do have some complaints if you don't mind.

I realized that most of the views have fixed widths—and in the case of the web-view, it seems to have fixed height.

1.) With the month view, the fixed width seems odd especially when comparing the plugin to the Calendar and Fantasy Calendar plugins, whose widths adjust based on the sidebar size. This is also the case with the schedule and timeline view (though I think it matters less with the latter).
<img src="https://user-images.githubusercontent.com/59588053/193004159-f56d6a65-325f-4d3f-96b9-890297a6d7b5.gif" height="300">

I'm aware that you can scroll horizontally but it's less convenient than seeing everything at once, especially compared to the aforementioned plugins.

---

2.) With the web view, Obsidian doesn't show the entire webframe; you'd have to place the mouse cursor on one of the GCalendar sidebars to scroll all the way down.
<img src="https://user-images.githubusercontent.com/59588053/193036256-ee68bfc8-1308-49ea-b82f-8329d893b20a.gif" height="350">

3.) This becomes more annoying with the month view on the web, where by default, scrolling changes months, but in this case, it scrolls and changes the month at the same time. This makes it hard to see what's going on because the month header and everything at the top is covered when the frame is scrolled all the way down.

<img src="https://user-images.githubusercontent.com/59588053/193036525-4e2e38cf-ded2-42d1-88b7-db57aa83302f.gif" height="400">

FWIW though, I did notice that the webframe adjusts according to the pane size, and if the pane is small enough, the problem is essentially gone, though the pane itself is too small to be usable most of the time:
<img src="https://user-images.githubusercontent.com/59588053/193040592-3ac41ac2-6cb8-4548-af44-0eb47e395cfc.gif" height="300"><img src="https://user-images.githubusercontent.com/59588053/193043119-15e95b07-facd-411a-88a5-78132dcf0729.gif" height="300">

---

Apologies if this is really long 😅 Thank you!

**Comment by YukiGasai** [comment]
@AngelusDomini thank you for the detailed issue.
Please check if the month and web view is now working as expected.

**Comment by AngelusDomini** [comment]
It's working as expected now. Thank you so much for the speedy update!
