### ISSUE TITLE
Use variable as prefix in event note filename

### ISSUE THREAD

**Issue by leoditommaso** [YukiGasai/obsidian-google-calendar#121]
Hi! First of all thanks a lot for this amazing plugin!

I was wondering if is it possible to add a prefix from a variable to the event note filename. What I'm trying to do is to append the date to the event note name.

<img width="724" alt="Screenshot 2023-05-10 at 15 16 56" src="https://github.com/YukiGasai/obsidian-google-calendar/assets/4322484/a2b2c8b4-3039-42cd-875f-593dc34ca8b3">

Best!

**Comment by YukiGasai** [comment]
Hi,
the prefix option is only to improve performance. You can just leave it empty and define your own.
Please check #42 and #43 for options.
You should be able to just use `{{event-date}}-{{event-title}}` or
`{{date}}-{{event-title}}` if you want the today's date.

**Comment by leoditommaso** [comment]
Thanks, that works great!
