### ISSUE TITLE
Feature Request: Insert Event data into daily note

### ISSUE THREAD

**Issue by vaibhav-kaushal** [YukiGasai/obsidian-google-calendar#123]
I am using this plugin and it has solved a lot of my problems. However I have now accumulated a good pile of meeting notes and all of them look haphazard in my notes. Earlier I used to plan my day using Daily Notes only but now it is split between that and Meeting Notes which look like a mess.

**Request**: Can we have a feature which inserts the event info into today's Daily Note instead of creating a new note for each event? 

It would be an amazing feature for people like who live by the calendar and want a summary of what all went in the day rather than having a dozen files for each day.

**Comment by YukiGasai** [comment]
There are a few options to do this already.

1. Insert data manually using `{{gEvent.[option]}}` after linking the event with the @Anotation
https://github.com/YukiGasai/obsidian-google-calendar/assets/38146192/5d2aca14-1790-425f-a6cf-a268400bbaf7
2. Using the `Insert gCal Event` Command with the table option to insert the selected events and the details as a table.
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/38146192/76539e93-56a5-45ba-b1b2-053c876a8a58)

4. Or use templater to insert the data using the API #13.
