### ISSUE TITLE
[Question] Change Schedule View Time Format?

### ISSUE THREAD

**Issue by Alcatraz077** [YukiGasai/obsidian-google-calendar#126]
Hello,

Is there a way to change how the time is displayed in the Schedule view? It's defaulting to 24 hour time, but all the devices I use are 12 hour, as is the calendar itself if I open up Google Calendar.

Schedule View of two events:
![Screenshot_20230526_122829](https://github.com/YukiGasai/obsidian-google-calendar/assets/21212254/7b501a2a-cf2a-48eb-81fb-d7d46bb9fddc)
Same event opened within the plugin:
![Screenshot_20230526_122852](https://github.com/YukiGasai/obsidian-google-calendar/assets/21212254/41c807a9-92fd-4075-a7df-e3ecbe0b4e73)

Thanks

**Comment by YukiGasai** [comment]
Hi,
you can press on the weekday name to switch the datetime format. In the future, this setting will be moved to the view settings.

**Comment by Alcatraz077** [comment]
Oh, thanks! Don't know why I didn't try that when I was clicking around. Good to know that there's a plan to put that into settings.

I'll close this out.
