### ISSUE TITLE
Question about the name of autocreated notes

### ISSUE THREAD

**Issue by qpinex** [YukiGasai/obsidian-google-calendar#128]
This is a great plugin, thanks!
I want to know what I should write in the "Event Note Name Format" field in the settings so that the Event Notes name contains the start time of the event (if it is not a Full day Event)
P.s. I tried {{event-time}} but it didn't work

**Comment by qpinex** [comment]
I tried to write these options in the "Event Note Name Format" (1 picture), but they do not seem to work (2, 3 pictures) 😢

![IMG_20230602_150708](https://github.com/YukiGasai/obsidian-google-calendar/assets/134804539/0ec5ee18-75fa-414e-a31c-7f2fe1c395ca)
![IMG_20230602_150530](https://github.com/YukiGasai/obsidian-google-calendar/assets/134804539/7ad1a244-30ef-4bd4-a90b-b07ca6a925d4)
![IMG_20230602_150352](https://github.com/YukiGasai/obsidian-google-calendar/assets/134804539/b1171639-cff0-4e50-8e18-b3ea02c5ab4e)

**Comment by YukiGasai** [comment]
What version of the plugin are you using. I added the feature with the latest version. 1.9.15

**Comment by qpinex** [comment]
Omg my bad, thank you. But now I realized that the auto-addition does not work at all if in the field "Event Note Name Format" write a symbol ":" (I wanted to put it between hours and minutes). I tried to do it three ways (as in the pictures):

![IMG_20230602_154437](https://github.com/YukiGasai/obsidian-google-calendar/assets/134804539/fef281c8-b8f7-41cb-ba7f-4ea407664995)
![IMG_20230602_154504](https://github.com/YukiGasai/obsidian-google-calendar/assets/134804539/73b5e3b3-7008-4350-862a-47acc7ba9e42)
![IMG_20230602_154527](https://github.com/YukiGasai/obsidian-google-calendar/assets/134804539/be7db929-0196-444d-8f88-ede2b3e97f77)

Events stopped being added after that

**Comment by YukiGasai** [comment]
That's because the note will create a file on you OS and windows doesn't allow : as character

**Comment by qpinex** [comment]
Maybe I can mark it with some special characters, like ":" or %:%, so that the system doesn't treat it as some kind of operator? (sorry, I am far from this topic)
If not, then I'll use "." between them 🙃
