### ISSUE TITLE
Bring to the front the red line of the timeline

### ISSUE THREAD

**Issue by ledzeg** [YukiGasai/obsidian-google-calendar#129]
Hello, I would like to know if it is possible to bring to the front the red line of the timeline, because it always appears behind the event blocks. As you can see in figures, the block "Project" is on top of the red line. Thanks in advance
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/107968926/8af4d41f-6865-40a7-9840-a5379f50df87)
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/107968926/f700377b-525c-44a7-9f1c-e017a6931085)

**Comment by sessionsdev** [comment]
I would also appreciate a fix for this.  I have tested on multiple themes, including default, and all behave identically.

**Comment by Carrasco-R** [comment]
+1 For this as well

**Comment by YukiGasai** [comment]
Hi,
I updated the plugin.
Please test it yourself, if everything works as expected you can close this issue.

**Comment by ledzeg** [comment]
Yes it works for me too, thanks @YukiGasai !
