### ISSUE TITLE
(feat req) Open first available link in Calendar Description

### ISSUE THREAD

**Issue by erauner12** [YukiGasai/obsidian-google-calendar#132]
Could you consider providing a means of opening the first available link in Calendar Description (in case there are multiple links).

Usecase:
- I use an app called [tascaly](https://tascaly.com/) that creates a link to a todoist task associated to each calendar event.
- I could see how this could be useful for zoom/teams as well though since these links are usually in the description.

Current Workflow:
- `type: schedule`
- left click the event -> copy link from description into clipboard
- open browser -> paste todoist link -> done

Desired Workflow:
- right click event -> Context menu option to "Open URL in description"
- left click event -> button inside of event window that would trigger this behavior? (opening the link of the first identified url)

I am not certain on the best way to implement this, please let me know if you have any thoughts on this (if you think it would be useful).

**Comment by erauner12** [comment]
I suppose another workflow upon thinking further is to "Show Single Event" and then click the URL from there.

**Comment by YukiGasai** [comment]
Hi, sorry for the late response.

Your use case is a little too specific for an additional feature.
I do understand the struggle of clicking the link tho.
The event description now renders the HTML elements inside it, so you can click links and view images.
To edit the description, you can use Markdown by changing from view mode to edit mode with the book button.
The markdown of the used library is not quite like the one used by obsidian, so some things may not work
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/38146192/805da05e-544c-4813-acab-24eee2a5267e)
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/38146192/4d766bdc-fee9-44da-a4af-47d383711d85)

**Comment by erauner12** [comment]
Nice! I'll check out this out! Thank you for the response.
