### ISSUE TITLE
schedule view not displaying multi-day events properly

### ISSUE THREAD

**Issue by pastorjack** [YukiGasai/obsidian-google-calendar#14]
I have an event that is Wed-Fri on my Google calendar. In the schedule view of the plugin, it only shows on Wed, but I would expect it to show Wed, Thu, and Fri.

**Comment by YukiGasai** [comment]
Hi @pastorjack I added the function. 
Please take a look if it works for you. 

The multiday events are view only, you can't update the original google calendar Event for now.

**Comment by YukiGasai** [comment]
I will close this issue for now. If there are any problems when viewing multi day events, we can reopen the issue.

For updating multi day events, just like for changing recurring events, I recommend using the web interface for now.
