### ISSUE TITLE
Feature Request: Set "Busy" or "Free" when creating and event from the Obsidian Create gCal event option

### ISSUE THREAD

**Issue by preslavnpetrov** [YukiGasai/obsidian-google-calendar#140]
It would be good to be able to set the "Busy" field on the event directly through obsidian when creating an event. I have a few shared calendars that people who I share it with can look at to see if I'm available or busy.

**Comment by YukiGasai** [comment]
Hi, 
I added a simple checkbox into the Details View
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/38146192/edd25fcc-4361-41e9-90b0-1a9b131b484d)
Please test it yourself.^^

**Comment by preslavnpetrov** [comment]
Thank you! Works as expected.
