### ISSUE TITLE
Feature Request: Create Reminders from within Obsidian

### ISSUE THREAD

**Issue by preslavnpetrov** [YukiGasai/obsidian-google-calendar#141]
Sometimes, instead of events, it's nice to instead create reminders in Google Calendar. That way, they don't clog up your actual agenda for the day, and you can get a notification on your phone for things that aren't actual events.

**Comment by YukiGasai** [comment]
Hi, 
I looked into this, but I couldn't find an API Endpoint for Reminders.
Please take a look at this [issue](https://issuetracker.google.com/issues/36760283) from the Google Issue Tracker.
For now, I think it's not possible, but maybe you find a legitimate way.
