### ISSUE TITLE
Documentation has incorrect wording

### ISSUE THREAD

**Issue by FitzM** [YukiGasai/obsidian-google-calendar#142]
In the documentation to setup the google calendar api step 9 says to search for "Google Enterprise API" however in the picture it shows clicking on the "Google Calendar API" which I believe is the correct API to search. 

![Screenshot_20230625_072856](https://github.com/YukiGasai/obsidian-google-calendar/assets/55612195/520ed598-c350-48cc-8cc9-c978a53484b2)

**Comment by YukiGasai** [comment]
Thanks, I updated the guidde.
