### ISSUE TITLE
Google Calendar Obsidian - Privacy Issue

### ISSUE THREAD

**Issue by valiantgenomics** [YukiGasai/obsidian-google-calendar#143]
I have a privacy-related question which I'm not sure can be answered definitively, but I'm curious to hear your perspective.

I'm using this awesome Obsidian plugin without linking it with a ClientID and ClientSecret, but simply by logging into my Google Calendar and using the iframe feature.

I have the iframe pinned to my Obsidian tab. **And was wondering how much, if anything, can Google see from the rest of my Obsidian vault?**

If the Google Calendar iframe is treated as a tab within a web browser, this would mean that Google can see everything I do in my Obsidian vault, simply because I have signed in to my Google calendar from within Obsidian.

Please let me know your thoughts!

**Comment by YukiGasai** [comment]
Hi,
that's a good question. TBH I haven't thought about this as much, but the electron webview should create an encapsulated area. It should be like a new browser instead of a new tab. 
If you are only using the webview I recommend using the [Obsidian Custom Frames](https://github.com/Ellpeck/ObsidianCustomFrames) Plugin as it focuses on creating this kind of views.

**Comment by valiantgenomics** [comment]
Brilliant! Thank you for your input! And thanks for recommending the custom frames plugin, haven't thought of using for this specific case.
But if one wants to integrate Google Calendar into their Obsidian vault, there's nothing even remotely as good as your plugin. I initially linked my calendar via the ClientID and ClientSecret and followed your documentation, but then disabled it due to Google privacy concerns. Regardless of that, the amount of work that must've gone into developing this plugin is nothing short of astonishing. Thank you for your selfless contribution to the FOSS community!

**Comment by YukiGasai** [comment]
Thank you 😊
