### ISSUE TITLE
schedule view: doesn't render

### ISSUE THREAD

**Issue by morulaus** [YukiGasai/obsidian-google-calendar#144]
Hi,
day/month/web views render without any issues for me but schedule produces nothing. this is what I use:

```gEvent
type: schedule
date: today
timespan: 0
```

**Comment by YukiGasai** [comment]
Please try timespan 1

**Comment by morulaus** [comment]
oh great, thank you for the superfast responce!

**Comment by morulaus** [comment]
Hi Yuki!,

after working for a while type: schedule stopped working and now shows nothing. the rest of the types work. my code is very basic:

type: schedule
date: today
timespan: 2

any ideas?
