### ISSUE TITLE
Issues finding associated note with same id as event from event 'click'

### ISSUE THREAD

**Issue by FitzM** [YukiGasai/obsidian-google-calendar#146]
Hello! I want to say I love your plugin and it's exactly what I've been looking for. 

I'm trying to create my own plugin that stems off your calendar.   It's to do "time blocking" in a way that I think makes more sense in general than what most people have implement. 

 The idea is basically, 
- when I click on an event in the calendar, I filter through the notes and find the assoicated note. 
- On the assoicated note I'm going to include frontmatter that will point my plugin to a different note of tasks I've created.
- Then that note is shown on a sidebar leaf.  

What's the best way to identify the note that is assoicated to the event I clicked on?  Currently I have an event listener that gets the currentTarget.id and parse through the front matter of all the notes and tries to match the id. This  doesn't seem to be working correctly though and I was hoping you could point me in a more direct way of identifying the note that is associated to the event.  Are the events that have been created stored somewhere specifically? Is there a better way to identify the specific event? 

Thank you. 

EDIT: I figured out some of the issues I've been having. Not every eventId for the visual calendar is related to the notes that are created for them. I'm not sure why this is and I haven't figured out what is different between event's where their Id matches and where they don't.  Do you have any insight into this?

**Comment by YukiGasai** [comment]
Hi,
I fully understand the confusion here.
The current process for checking if an event has an event-note is divided into 2 parts. It's very messy and I would like your opinion if this should be made easier.

## First Option
1. Check if an event name is matching a file name in the vault.
2. All the files that are possible options are checked if they contain an event-id.
If a file with event-id is found, it is chosen over the other files.
If no file with event-id is found, the first one is chosen and it is marked that this match is only based on filename.

## Second option
1. The vault checks all files for an event-id
This process is supported by the setting Prefix that can be used to search the vault faster.
2. Same as Option 1.


I am thinking about removing all of this complex stuff to a more simple, less performant solution. This would mimic the idea that you already come to. The benefit would be, that if a file is found you can be 100% sure that it is for exactly the one event and not a list of events.
