### ISSUE TITLE
How to select only specific calendar to be displayed?

### ISSUE THREAD

**Issue by Rhydderch** [YukiGasai/obsidian-google-calendar#15]
Thank you for this plugin.

I am connected to several calendars, some I don't use.
How to select only specific calendars to be displayed?

**Comment by YukiGasai** [comment]
You can add calendars you don't want to see to the blacklist in the settings.

**Comment by JHenzi** [comment]
Hey @YukiGasai - that works well, but curious if you see value in enhancing the code block to include or exclude calendars when it runs? In my use case the company has calendars open typically and we add each others to be informed - however I wouldn't want to pull in my boss's meetings when I'm starting out in my daily note and planning my day. It's great to know but causes clutter on your _**beautiful**_ interface. As I'm adding the code block and the templater formats to my workflow I'm seeing the beauty of this even more, love the work!

**Comment by YukiGasai** [comment]
Hi @JHenzi I think I understand.
You want to see all the calendars in for example the month view in your work notes. But when you open your daily notes and you have for example another month view there, you only want to see your personal calendars.
Is this the idea?

I could imagine a list of calendar names or id's as an optional black or whitelist.

**Comment by YukiGasai** [comment]
With the new options `exclude` and `include` this issue should be resolved.

Example codeblock including only specific calendars:
\`\`\`gEvent
date: 2022-11-08
type: day
include:
\- Leben
\- Richard
\`\`\`
