### ISSUE TITLE
Events show twice in all views

### ISSUE THREAD

**Issue by mimimalisma** [YukiGasai/obsidian-google-calendar#156]
Hey everyone,
I am facing the issue that all events created in Obsidian show twice in all calendar views.
Do you have an idea what might be the cause of this?

![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/129988726/9809031b-2d5c-4db0-a87d-10f411ca8293)

**Comment by FelixGonzalez42** [comment]
i've the same bug:
Obsidian:
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/64332131/cbc2b445-2b15-49d3-a1c3-9f17850fbf50)
Google calendar:
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/64332131/a23d98b2-d00f-4965-97e1-088ca600bcae)

**Comment by YukiGasai** [comment]
Hi,
I was not able to reproduce this by just creating a new event. 
Are you using some special settings in the event?
What kind of views are open when creating this event?

I am guessing it's some kind of caching issue where an event is added manually and retrieved from Google at the same time.

**Comment by FelixGonzalez42** [comment]
Hello,
The problem disappeared for me, I can't reproduce it again, that you for the support.
 
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/64332131/094bf6d1-366e-48a1-a2b8-2c940c4b7c65)

**Comment by mimimalisma** [comment]
Hey there,
I tried to reproduce it, but somehow the problem seems to have solved itself since it  all works like it should now.
Maybe it was not plugin related at all :)

Anyways, thanks a lot for providing both the plugin and the support!
