### ISSUE TITLE
Cannot logging, total newie

### ISSUE THREAD

**Issue by amglez** [YukiGasai/obsidian-google-calendar#157]
I hope I did everything as instructed.
When I try to login I get:
![imagen](https://github.com/YukiGasai/obsidian-google-calendar/assets/24720353/ee717a84-e3b1-4c5b-912a-16519de2f519)

I saw the other (closed) issue, but I did not see the ip in the cmd promt.

Hope you can help. The plugins look very nice.

**Comment by YukiGasai** [comment]
Hi, 
can you show me the redirect URL you have used in the registration process in google?

**Comment by Artem-627** [comment]
@YukiGasai do you mean this URL?

https://accounts.google.com/signin/oauth/error?authError=ChVyZWRpcmVjdF91cmlfbWlzbWF0Y2ggkAMyAggB&client_id=448286990722-q12gvtnog3hvtrru389qvkvc1j2tugad.apps.googleusercontent.com

**Comment by YukiGasai** [comment]
Sorry for the late response, please show me your google cloud project configuration. Example:
![](https://user-images.githubusercontent.com/38146192/269669420-e3ddbf0c-7bea-4772-a299-fd26029ca897.png)
Are you using the plugin on desktop or mobile?
