### ISSUE TITLE
"Open Event Note" is showing when note was not yet created

### ISSUE THREAD

**Issue by machado-t** [YukiGasai/obsidian-google-calendar#159]
When you click an event, I suppose it should show either the "Create Event Note for this date" or the "Open Event Note" button.
In my case, both are present when the note was not yet created. Clicking "Open Event Note" opens an unrelated note if one was not created yet.

**Comment by machado-t** [comment]
I think this was already solved, no?

**Comment by YukiGasai** [comment]
True 😅
