### ISSUE TITLE
Month view sometimes not rendering events properly

### ISSUE THREAD

**Issue by AngelusDomini** [YukiGasai/obsidian-google-calendar#16]
I noticed that the month view does not render events (dots) properly sometimes. This is usually fixed by reloading the Obsidian app, turning the plugin off then on, or closing and reopening the month view; but ideally the user shouldn’t have to do this.

Here are some of the issues I’ve noticed when events aren’t rendered properly:

### Shows same event twice/thrice in a day (two/three dots instead of one):

<img src="https://user-images.githubusercontent.com/59588053/195623589-e3f09e05-5348-4244-ae56-ae671336f75c.png" height="350"> <img src="https://user-images.githubusercontent.com/59588053/195626812-d783d171-5dfb-40a3-b710-496363cd8e14.png" height="350">

This usually happens when creating new events, whether using the plugin to do so or from Google Calendar web.

### Not all events appear (not showing dots on days when there are supposed to be events)

While most events show up, I noticed a few that don’t.

<img src="https://i.imgur.com/RRB3DUi.png" height="350"> <img src="https://i.imgur.com/C6mPQOC.png" height="350">

This is rather unpredictable, so idk how to reproduce this.

### Current day not updating on 12AM

The web view does not update the current day when it is 12AM. E.g., on October 14 at 12:01 AM, the month view still shows October 13 as today’s date unless I reload Obsidian. I’m not sure whether the other views (timeline, schedule) do this also.

I also don’t know whether other calendar plugins are able to update the current date at 12AM, so this problem might not be unique to this plugin.

Also, if this constitutes as a separate issue, lemme know.

### Events from previous and next month not showing on current month

If I have events on, say, November 1-5 of 2022, I would want to be able to see these events while it’s still October 2022.

<img src="https://i.imgur.com/EksJAkb.png" height="350"> <img src="https://i.imgur.com/vccgriO.png" height="350"> 

Since, currently, these events aren’t shown on the current month, I wouldn’t be able to know if there are events on these days unless I deliberately checked the next month. I’m aware that the Calendar plugin can show dots on the previous month of the current month being displayed.

**Comment by pastorjack** [comment]
I think this update is broken.
trying to install through BRAT
`BRAT: YukiGasai/obsidian-google-calendar
The release is not complete and cannot be download. main.js is missing from the Release
`
trying to install the normal way through obsidian
`app.js:1 Error: Request failed, status 404
    at new t (app.js:1:699529)
    at nw (app.js:1:699721)
    at app.js:1:700398
    at app.js:1:235201
    at Object.next (app.js:1:235306)
    at a (app.js:1:234045)`

**Comment by YukiGasai** [comment]
Thank you @pastorjack for telling me. #17 should work again.

**Comment by AngelusDomini** [comment]
Have installed the latest update of this plugin for a while now, and so far
all of the problems I talked about here have been resolved. Thank you so
much @YukiGasai!

**Comment by YukiGasai** [comment]
Sounds good.
If you see the problem returning, simply reopen the issue. I'm closing it for now.
