### ISSUE TITLE
Adding "blacklist" item only adds one at a time

### ISSUE THREAD

**Issue by lenalebt** [YukiGasai/obsidian-google-calendar#163]
**Steps to reproduce:**

- add multiple blacklist items at once in the settings UI

![grafik](https://github.com/YukiGasai/obsidian-google-calendar/assets/697104/75b9f02e-7419-4e7f-9745-8b02e4f2f459)

**Expected behaviour:**

- all items are added to the blacklist

**Actual behaviour:**

- only one item is added to the blacklist, the others are skipped
- if you repeat the process, you can add multiple elements

**Comment by YukiGasai** [comment]
Hi, I updated the plugin, can you please test if it works for you now.

**Comment by lenalebt** [comment]
Hey @YukiGasai, I can confirm it working, thank you very much :-)!
