### ISSUE TITLE
1 Event is shown as 2 Event

### ISSUE THREAD

**Issue by tea-enjoyer11** [YukiGasai/obsidian-google-calendar#164]
Hello,
for some reason if i create an event it shows up as 2. But only in obsidian, can you help me here? Maybe im missing something...

btw, thanks for your amazing plugin!

https://github.com/YukiGasai/obsidian-google-calendar/assets/128899868/0255e9b4-248a-4ada-95e0-b86bbdf55554

**Comment by YukiGasai** [comment]
Hi, 
I was able to reproduce this by switching between calendars.
I updated the plugin, so it no longer happens for me.
Can you please test it on your end?

**Comment by tea-enjoyer11** [comment]
sorry for the late reply.... i forgot about this topic.
Through your update my problem is now gone!! thanks a lot!
