### ISSUE TITLE
newbie. Webview is showing google webspace page, asking for login

### ISSUE THREAD

**Issue by chocochocosensei** [YukiGasai/obsidian-google-calendar#165]
I was able to set it up and in my day, month, etc view all is okay. But in webview:

<img width="781" alt="Screen Shot 2023-08-09 at 9 50 48 AM" src="https://github.com/YukiGasai/obsidian-google-calendar/assets/39887116/98da7efb-56e3-4d3b-bff1-e829f2f93dcd">

I get this:
<img width="689" alt="Screen Shot 2023-08-09 at 9 50 56 AM" src="https://github.com/YukiGasai/obsidian-google-calendar/assets/39887116/740f6c3e-e05b-4033-84ab-7344efe40cde">

and if I click the sign in link I get thrown outside of Obsidian, so I can't log in.

I tried using the "surfing" plugin to force links to load in obsidian, but no luck.

What to do?

Aside: I feel the documentation is a bit scanty.  You could be more specific about what formats dates should be in. For example, I see that dates like "next thursday" work (or is that the tasks plugin working?,  but this is not mentioned, as far as I can see. Things like setting date with webview (which ppears not bto be working for me) also not explained.

**Comment by YukiGasai** [comment]
Please check out #116. 
Open the web view  and use the login button in the settings.

I understand that the documentation for this plugin sucks but because this is only a hobby project I just can't get myself to fix this.

**Comment by ksdavidc** [comment]
Thanks. Got it working finally. Logging in (again) helped, and waiting for things to update, I guess. 

Still no luck with date on webview. Maybe it's not possible.

I understand where you are coming from. I am in the same boat, but thanks for the helpful reply. Hang in there.
