### ISSUE TITLE
schedule view shows event, then inexplicably event disappears

### ISSUE THREAD

**Issue by chocochocosensei** [YukiGasai/obsidian-google-calendar#166]
https://github.com/YukiGasai/obsidian-google-calendar/assets/39887116/22c3d2ac-8540-4b07-89e9-ed8317605756

**Comment by machado-t** [comment]
This may be the same as [this](https://github.com/YukiGasai/obsidian-google-calendar/issues/133)

**Comment by YukiGasai** [comment]
Is this issue still occurring in the updated versions of the plugin?

**Comment by machado-t** [comment]
Not in my end.
