### ISSUE TITLE
Make gEvent available to Templater

### ISSUE THREAD

**Issue by califa** [YukiGasai/obsidian-google-calendar#167]
Hey, new to Obsidian here so apologies if this isn't a reasonable ask, but is there a way to make the json object available to Templater for more advanced manipulation? For instance I'm trying to remove all Zoom info from the description, and to parse attendees with some logic, and to place both in collapsed callouts.

In general, I'm getting this error when I try to use Templater syntax in the template for this plugin. 
(like `<% {{ gEvent.attendees }} %>` or `<% gEvent.attendees %>`.

![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/602352/8bce854f-cc40-4370-a0a0-61c022939c00)

Thanks a ton, and thank you for maintaining this!

**Comment by YukiGasai** [comment]
Hi, this is already possible using the API.
Here are some [examples](https://github.com/YukiGasai/obsidian-google-calendar/discussions/110).

**Comment by califa** [comment]
The best response I could have hoped for! Thanks so much!
