### ISSUE TITLE
Add option to ignore events with specific keywords

### ISSUE THREAD

**Issue by califa** [YukiGasai/obsidian-google-calendar#169]
I'm looking to import all of my meetings (I'm connecting these with "people" notes to create a graph of when I've seen people). 

The problem I have many meetings in my calendar that don't make sense to important—blocks of time to do a task, "do not schedule" time blocks, HOLDs for meetings, or recurring reminders to do something. Some of these have to be on the same calendar as important meetings.

Would it be possible to add a feature that's like the opposite of an event marker, where I can list a few keywords that, if they appear in an event title, mean it won't get imported?

Thank you so much! Love the plugin so far :)

**Comment by califa** [comment]
Ooh thank you!!

**Comment by califa** [comment]
Would it be possible to apply this to anywhere that imports events? Like not listing events with these keywords in `Create Event Note` or `List gCal Events`

**Comment by YukiGasai** [comment]
Hi, I implemented your idea.
I updated the `autoCreateEventNotesIgnoreList` setting to `ignorePatternList`.
The behavior should be the same, but it will filter all events right after they are fetched from Google, so the plugin should not show them anywhere.
You will have to set the list again, I think, but I had to update the name to fit better with the behavior.
