### ISSUE TITLE
Getting 404 on update or install

### ISSUE THREAD

**Issue by rapatel0** [YukiGasai/obsidian-google-calendar#17]
Trying to update and it fails to load

Installation Attempts:
- Tried to update installed plugin
- Uninstaled plugin and tried to install from scratch 

Both attempts failed
<img width="321" alt="image" src="https://user-images.githubusercontent.com/18704704/197199807-35376ba0-aa13-43ae-987e-3612a388188f.png">

Shows this in console
<img width="669" alt="image" src="https://user-images.githubusercontent.com/18704704/197199420-570991fe-f891-4f22-a8c4-91dd90886779.png">

**Comment by davidberreby** [comment]
Same here. Closed Google Calendar tab in Obsidian, then restarted and tried again to update. Same failure. Then, logged out of Google, restarted obsidian, logged back into Google Calendar via the plugin's login option, then retried update. Failed again. 

The plugin, though it failed to update, still appears to work normally.

**Comment by YukiGasai** [comment]
I forgot to push the new release. 😅
Sorry for the inconvenience, please try again.

**Comment by davidberreby** [comment]
All good now! Thanks!
