### ISSUE TITLE
Multiple days event just show up as one day event in the cal.

### ISSUE THREAD

**Issue by SecurityDog88** [YukiGasai/obsidian-google-calendar#170]
Hi,

like the title says. I have an event for 2 1/2 weeks (vacation - whole day event) and only the first day shows up.

![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/135823938/5dbb185d-f939-4d49-ad21-40755af6715c)

I use this code.

```
gEvent
type: week
```

**Comment by YukiGasai** [comment]
Thank you for bringing this issue up.
I didn't know there were full day events over multiple days.
I am working on a fix ^^

**Comment by YukiGasai** [comment]
Hi, I updated the plugin, please take a look if your issue is fixed.
