### ISSUE TITLE
Feature request: Option to have "Create gCal Event" menu in right side ribbon pane

### ISSUE THREAD

**Issue by JayamanideepR** [YukiGasai/obsidian-google-calendar#173]
Hi!

This is a really great plugin and many thanks for that.

While creating events using this plugin, I often have to refer to dates and content from my notes.
So, it would be awesome to have access to them while creating the event. I think one way to achieve that would be to have an option that makes the menu showup in the right ribbon pane

**Comment by YukiGasai** [comment]
Hi, I added this feature.
You can use the Command `Create gCal Event inside View` to open the Details View on the side.
This View can also be open if you Shift Left Click Events inside views.

**Comment by JayamanideepR** [comment]
Awesome!
Thank you for creating this feature.
