### ISSUE TITLE
Feature Request: Add additional filters to event parameters

### ISSUE THREAD

**Issue by mmmyah** [YukiGasai/obsidian-google-calendar#177]
I really liked the schedule view of the plug-in and it would be perfect for my workflow if we could filter the events by location or tags. As of the time of this post, I just use the plug-in to view all the events together in one calendar.

**Comment by YukiGasai** [comment]
Hi,
you can filter the displayed calendars and the events by color using the `include` or `exclude` option.
~~~
```gEvent
date: 2023-08-30
type: schedule
include: ["Banana", "Peacock"]
```
~~~
Could this be enough for your usecase?
What do you mean with tag?
