### ISSUE TITLE
Google Events could not be loaded

### ISSUE THREAD

**Issue by Stefanando** [YukiGasai/obsidian-google-calendar#178]
I followed step by step your indications, thanks! But when I restart Obsidian the plugin doesn't work and it appears the above error: "Google Events could not be loaded". What could I missed? Thanks, Stefano

**Comment by Stefanando** [comment]
[GoogleCalendar] Error: Error Google API request
    at eval (plugin:google-calendar:25:44286)
    at Generator.next (<anonymous>)
    at o (plugin:google-calendar:6:1197)

**Comment by YukiGasai** [comment]
Please enable Debug Mode in the Settings and check again.

**Comment by Stefanando** [comment]
[GoogleCalendar] Error: Error Google API request
    at eval (plugin:google-calendar:25:44286)
    at Generator.next (<anonymous>)
    at o (plugin:google-calendar:6:1197)

**Comment by Stefanando** [comment]
![calendar_error_log](https://github.com/YukiGasai/obsidian-google-calendar/assets/143658277/dd082d9b-0516-4d22-a83e-19c00f0e2aa4)

**Comment by Stefanando** [comment]
Noi it seems to work...

**Comment by blisst** [comment]
Getting the same error.  Brand new OAuth credentials.

<img width="551" alt="Screenshot 2024-11-23 at 14 02 33" src="https://github.com/user-attachments/assets/fc92ebb5-2e94-4690-be23-f16fad8d2c7e">

<img width="540" alt="Screenshot 2024-11-23 at 14 03 04" src="https://github.com/user-attachments/assets/de48bb92-eafd-43b9-9736-12947526cc76">


Here is the `curl` with the redacted auth token that generates the error:

curl 'https://www.googleapis.com/calendar/v3/users/me/calendarList' \
  -H 'authority: www.googleapis.com' \
  -H 'accept: */*' \
  -H 'accept-language: en-US' \
  -H 'authorization: Bearer ya29.a0AeDClZA4Kk0s....' \
  -H 'content-type: application/json' \
  -H 'origin: app://obsidian.md' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.5.3 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36' \
  --compressed
