### ISSUE TITLE
old codeblocks no longer working

### ISSUE THREAD

**Issue by pastorjack** [YukiGasai/obsidian-google-calendar#18]
Hi!
I used to have this in my daily note:
`
```gEvent
type: schedule
date: 2022-10-21
```
`
now it shows the "day" type view instead of the "schedule" view
but if I insert this, it works
`
```gEvent
date: 2022-10-21
type: schedule
timespan: 0
```
`
If type is the first item, it will only display the day view for me. But if I put date first, it works as expected.

**Comment by YukiGasai** [comment]
Sorry, but I can't reproduce this problem. For me this

\`\`\`gEvent
type: schedule
date: 2022-10-19
\`\`\`

works as expected. 
Can you please give another example.

**Comment by YukiGasai** [comment]
Please make sure there are spaces between the colon and the option text.

I'm sorry, the problem is that I updated the code to pare the options inside the code blocks better. The syntax is now `yaml` based to allow lists for excluding and including calendars #15 .



```gEvent
type: schedule
date: today
timespan: 3
```

**Comment by pastorjack** [comment]
Beautiful. Problem solved. Thanks!!!
