### ISSUE TITLE
Text is cropped inside events if words are too long

### ISSUE THREAD

**Issue by m-beau** [YukiGasai/obsidian-google-calendar#180]
Self-explanatory:

![Screenshot from 2023-08-31 16-47-56](https://github.com/YukiGasai/obsidian-google-calendar/assets/25953361/ed0bf14a-ee5e-45b1-8550-c1092b1fd866)

**Comment by YukiGasai** [comment]
Hi,
the text is cropped to the top of the box to increase the chance of being readable if other events overlap it.
If you have a better idea, please give it a description.

**Comment by m-beau** [comment]
I agree that the portion which is currently visible should stay at the top, but the cropped-out letters are doomed to be invisible in any case.

I suggest 1) allowing to set font size as a setting 2) 'wrapping' the text, google sheet style (but with a dash where the text got cut instead of nothing at all, I find that a bit confusing as well):
![gif2](https://github.com/YukiGasai/obsidian-google-calendar/assets/25953361/6ff152cf-c577-4e0b-90da-b66cc1a8057d)

**Comment by m-beau** [comment]
Also, related suggestion: you should decrease the space between lines and the margins in general - ideally dynamically based on the size of the box, even smaller is the box is way too small - to increase the room for the text to fit in each box! Check out how google calendar does it:

![Screenshot from 2023-09-01 11-11-38](https://github.com/YukiGasai/obsidian-google-calendar/assets/25953361/ef13be1e-2f0d-48bc-8698-57be7e4a829a)

**Comment by YukiGasai** [comment]
Hi, 
I updated the plugin, so the padding will be turned off if there is less space + I enabled text wrapping, so no words are cut off. I tried adding hyphens, but this doesn't seem to work and tbo would only take away space.

**Comment by m-beau** [comment]
text-wrapping without hyphens is better I agree

I would still suggest a smaller padding between rows of text (could be set as a parameter in the plugin preferences?)

**Comment by YukiGasai** [comment]
I try to avoid placing appearance options in the settings because, everyone has their own preferences and this would lead to more and more settings.
You can change the line Height of the text to put the rows closer together using a custom CSS Snippet.

```css
.googleCalendarName {
	line-height: 1;
}
```

**Comment by m-beau** [comment]
Fair enough - thanks for the snippet and the updates.
