### ISSUE TITLE
Feature request: clickable links in description

### ISSUE THREAD

**Issue by m-beau** [YukiGasai/obsidian-google-calendar#181]
Support for the [[obsidian_note]] syntax (opening a dropdown box as in regular obsidian) would be great!

**Comment by YukiGasai** [comment]
Hi, I updated the plugin, so you can click on Obsidian Links in the description.
Because the input element has no access to the editor with all its function, creating a dropdown file select is not planned.

**Comment by m-beau** [comment]
awesome cheers!

Would be then dope to have the option to show the description in small prints below the event title (with a toggleable tick box in the event pop up window). A use case for me would be to a small clickable 'x' below the event title, jumping to the right obsidian note. Alrenatively, support for clickable obsidian links in the even title itself would be great (in general, having the ability to click on the calendar view without opening a popup window and jump to an obsidian note would be cool)

**Comment by m-beau** [comment]
This works! Thanks a lot.
