### ISSUE TITLE
Issue with the new properties and Google Calendar

### ISSUE THREAD

**Issue by MelodyDuplaix** [YukiGasai/obsidian-google-calendar#182]
Since updating with properties, I've noticed a display bug with properties in date format, with the date calendar superimposed on the date:
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/131142776/f1095b2a-2bae-45a1-ae49-1775409ddef7)
After deactivating and reactivating them all, I was able to confirm that this bug came from the google calendar plugin, it disappears when I deactivate google calendar. Is it possible to fix this bug?

**Comment by MelodyDuplaix** [comment]
I noticed that the problem is in this part of the css, but I don't know where exactly :
```
 input[type='date'],
input[type='datetime-local'] {
	background: var(--background-modifier-form-field);
	border: 1px solid var(--background-modifier-border);
	color: var(--text-normal);
	font-family: inherit;
	padding: 5px 14px;
	font-size: 16px;
	border-radius: 4px;
	outline: none;
	height: 30px;
} 
```

**Comment by YukiGasai** [comment]
Thank you for finding this.
I moved the CSS to component level. With the next release, this should be fixed :)
