### ISSUE TITLE
Ability to switch calendar post-event creation

### ISSUE THREAD

**Issue by m-beau** [YukiGasai/obsidian-google-calendar#184]
Currently, after an event is created, it is impossible to change its calendar from the dropdown menu. It is only possible when the even is created for the first time.

**Comment by YukiGasai** [comment]
Hi, I updated the EventDetails View to allow updating the calendar post event creation.
The problem is, that the calendar can't be updated with the same endpoint as the rest of the values.
I fixed this by updating the api as soon as another calendar is selected.
Please test it yourself.
