### ISSUE TITLE
Using Templater with getEvents has stopped working

### ISSUE THREAD

**Issue by mattwhetton** [YukiGasai/obsidian-google-calendar#187]
I've been using a template with Templater for a few weeks now and its been working just fine, but has stopped working inb the last few days.

My templater code looks like this:

`const {getEvents} = this.app.plugins.plugins["google-calendar"].api;`
`const events = await getEvents();`

Whenever I try to run this I now get an error in the console:

`
Error: Request failed, status 400
    at new t (app.js:1:265507)
    at sn (app.js:1:265699)
    at app.js:1:266375
    at app.js:1:237002
    at Object.next (app.js:1:237107)
    at a (app.js:1:235825)
`

Has something changed or an issue been introduced? This was work this time last week

Matt

**Comment by YukiGasai** [comment]
Hi,
I tested your template, but was not able to reproduce your problem.
Do the other views the plugin adds work?
Have you set a default calendar in the settings?

**Comment by mattwhetton** [comment]
Think I've had 2 issues confusing me

- You were right - somehow the default calendar had become unselected.
- Second problem was some conflict with the Fleet Notes plugin which I can resolve by put my fleeting notes sync in a different place

Apologies and thanks for the help
