### ISSUE TITLE
Darken events that have passed, like google calendar

### ISSUE THREAD

**Issue by sickerin** [YukiGasai/obsidian-google-calendar#189]
- Darken events that have passed.
- The red line indicating the current time seems to be hidden by events

![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/12108084/90987a81-48b0-41ef-b752-ca257363ec2e)
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/12108084/a9515891-fd06-42dc-8a22-a6c6753dcf28)

I can also look into implementing these, if they aren't.

**Comment by YukiGasai** [comment]
Hi, I added an extra Class for past events `googleCalendarEvent_Past`.
Past events will now get transparent.
If you want to change this, you can use a custom CSS snippet.
