### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by Victor1266** [YukiGasai/obsidian-google-calendar#19]
Hello! How to implement dark theme into this plugin?

**Comment by YukiGasai** [comment]
Hi,

the plugin should automatically adapt to the theme. If there are parts that don't, please give an example.

**Comment by Victor1266** [comment]
![image](https://user-images.githubusercontent.com/18232879/199283247-2ecfb1b7-4d00-4378-be56-08525bfb462c.png)
I have the default dark theme of the obsidian. But the google calendar appears white

**Comment by YukiGasai** [comment]
Hi,
I added a dark mode for the web view.
If you give me the CSS you would like to add to the view, I can add it as an extra theme.
You can set the default theme in the settings and if you use the webview as codeblock can set the theme attribute to set it. Possible values are `dark`, `light`, `auto`, (maybe your theme) 

Do you think it is better to close the left sidebar by default to get more space?

**Comment by Victor1266** [comment]
Updated the plugin and found the setting to select the default theme. Now is perfect, thank you!

Regarding closing the left bar, I think you are right 😂
