### ISSUE TITLE
Create Event Note problem with properties

### ISSUE THREAD

**Issue by panter-dsd** [YukiGasai/obsidian-google-calendar#191]
Hi! I've faced a problem with new properties in obsidian. I have this template:
<img width="655" alt="Screenshot 2023-09-19 at 10 29 44" src="https://github.com/YukiGasai/obsidian-google-calendar/assets/208976/d202e266-f1fc-4167-8622-74885ac31685">

And when I use this template for an event note creation I get
<img width="655" alt="Screenshot 2023-09-19 at 10 30 27" src="https://github.com/YukiGasai/obsidian-google-calendar/assets/208976/c7e54486-16a2-4055-b63a-06c2f03df56f">

I've recorded a video with this bug: 

https://github.com/YukiGasai/obsidian-google-calendar/assets/208976/287cbbb4-a60f-4369-8a3d-6ac139629226

**Comment by YukiGasai** [comment]
Hi, 
can you please show me the template in pure source mode?
You can change this in Settings → Editor → "Properties in document" = Source.
It looks like your template contains two frontmatter sections.

**Comment by panter-dsd** [comment]
```
---
date: <% tp.date.now("YYYY-MM-DD") %>
---
<% tp.file.rename(tp.date.now("YYYY-MM-DD") + ' ' + tp.file.title) %>
🏷️Tags: #meeting 
📅Date: `= this.date`
👥Participants: [[Konstantin Konnov]]

# Agenda

# Notes
```

**Comment by panter-dsd** [comment]
And the created event

```
---
event-id: 0us19egojc8oapt4k3cnnsb82p_20230919T073000Z
---
---
date: 2023-09-19
---

🏷️Tags: #meeting 
📅Date: `= this.date`
👥Participants: [[Konstantin Konnov]]

# Agenda

# Notes

```

**Comment by YukiGasai** [comment]
Thank you,
I was able to reproduce and I think is related to #168.
I will to fix it now ^^.

**Comment by YukiGasai** [comment]
If you want a quick fix for yourself, you have to add `event-id` manually to the fields, like shown in the related issue.

**Comment by panter-dsd** [comment]
Oh, it's not a problem right now. But I'll wait a fix. It's a bit bothering when you have to edit properties after note creation but it's not so criminal.

**Comment by YukiGasai** [comment]
I updated the plugin.
Please give it a try ^^

**Comment by panter-dsd** [comment]
Yep, it does work! Thank you @YukiGasai!!!
