### ISSUE TITLE
URI Error on Android only

### ISSUE THREAD

**Issue by bhemmelgarn** [YukiGasai/obsidian-google-calendar#192]
I have successfully logged in on a PC and a Mac, but on Android I get Error 400: redirect_uri_mismatch. 

Is there a URI that I need to add for mobile? Or is there some other issue going on?

**Comment by bhemmelgarn** [comment]
I don't think that's the problem; as is, clicking login takes me to the external web app to authorize the Google login, but that's where I get the uri_mismatch error. 

According to the link in 32, [Setting up OAuth 2.0](https://developers.google.com/identity/protocols/oauth2/native-app), it looks like "Android" is for setting up OAuth from inside Obsidian. I think that would require some heavy work to accommodate, when the web app should redirect just fine.

**Comment by grayerbeard** [comment]
I agree that using Android instead of web app at step 32 cannot be the answer.

For me the log in one does from set up works but something not working when the app is restarted I get an error message and if I try and execute a command , e.g to bring up a list of events, I just get a blank list.
Every time the app is started I get a message saying that there is an error.

**Comment by YukiGasai** [comment]
Hey,
I tested it myself and can reproduce your result. 
The problem is, that I accidentally updated the mobile callback to a url. This new url is used for the updated OAuth process from the other branch.
I will update the plugin to go back to the correct documented URL. Sorry 😐

**Comment by YukiGasai** [comment]
Okay, I checked again and saw that I updated the documentation.
Have you added `https://google-auth-obsidian-redirect.vercel.app` as Javascript Source URI and 
`https://google-auth-obsidian-redirect.vercel.app/callback` as Redirect URL?

**Comment by grayerbeard** [comment]
This pic shows the settings that I have always shad since I set it up on September 11th (and it worked always Ok on my Laptop but not Android)

Client ID for Web application
URL1    http://127.0.0.1:42813
URL2    https://google-auth-obsidian-redirect.vercel.app

Authorized redirect URIs
http://127.0.0.1:42813/callback
https://google-auth-obsidian-redirect.vercel.app/callback

**Comment by YukiGasai** [comment]
I wish it was that easy, but my first comment was kind of wrong, the switch to the new URL already happened and should work. I tested with two phones and my login works.
What version of the plugin are you using?

**Comment by grayerbeard** [comment]
I am on version 1.10.5 on my phone and 1.10.4 on my Laptop..  On phone if I go to plug in and go where the id and secret are and log in seems to log in etc ok but does not show any info if execute a command.  When Obsidian starts get message That Plug in "Not logged in or settings missing".  On Laptop seems to work from a command but does not show any of the events that are set in my Google Calendar.

**Comment by YukiGasai** [comment]
Wait so you don't get the Error 400: redirect_uri_mismatch?
In that case, please check for any errors in the Developer Console `Ctrl` + `Shift` + `i`.
You can also check if the Access and Refresh Token are stored in the Local Storage of the Obsidian application.
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/38146192/d53bb166-fb6b-489d-9a17-8a4dbcec9b3e)

**Comment by YukiGasai** [comment]
The hotkey should work on your laptop.

**Comment by grayerbeard** [comment]
Yes fine on laptop all works there, also now managed to install on my Android Tablet and all works fine.   I am now fairly sure the problem is the type of phone its an Xiaomi Redme Note 9 with Xiaomi's own query version of Android which I have found particularly frustrating sometimes with respect to settings (such as default apps) being missing altogether.  I am inclined to give up especially as my Little Tablet is OK.

**Comment by YukiGasai** [comment]
Thank you for your testing. I can completely agree with you here. I used the Redmi Note 8 and it was so bad that I decided to switch to a pixel. A last point of error could be that the browser doesn't allow the obsidian application to start when the OAuth process in the browser is finished and the browser is redirected to `obsidian://....`.

**Comment by bhemmelgarn** [comment]
For the record, I have a Pixel Pro 7, running version plugin 1.10.5 with both of the specified URI's. I don't think they're revealing, but screenshots attached. 

In Obsidian, I can create new events, but they don't sync and I can't import existing events. I can try to get into the mobile dev console for more info, but it will probably be a couple days until I have the time. 

![Screenshot_20230921-080358](https://github.com/YukiGasai/obsidian-google-calendar/assets/105377782/68a3e1f4-40a2-4cd2-b1af-b4e1f59a597d)
![Screenshot_20230921-080349](https://github.com/YukiGasai/obsidian-google-calendar/assets/105377782/4cdebbcc-9651-4436-a182-d4186050c926)

**Comment by bhemmelgarn** [comment]
![Screenshot_20230921-080349~2](https://github.com/YukiGasai/obsidian-google-calendar/assets/105377782/21e9df0c-c884-4405-ab8c-b8ecdedc363b)
![Screenshot_20230921-080358~2](https://github.com/YukiGasai/obsidian-google-calendar/assets/105377782/6ae15f40-d1e8-4266-8c30-f3ec215d2f6c)

**Comment by YukiGasai** [comment]
Hi @bhemmelgarn,
from your screenshots, it looks like the correct URL is used. But it seems like there is a problem with the configuration. Can you please send a screenshot of the Google cloud configuration page.
Example:
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/38146192/e3ddbf0c-7bea-4772-a299-fd26029ca897)

**Comment by bhemmelgarn** [comment]
It is an exact match. I tried to force https, but debugged that out on desktop. 

<img width="558" alt="image" src="https://github.com/YukiGasai/obsidian-google-calendar/assets/105377782/63985181-8e87-493b-9c57-b1ccb0afad0a">

**Comment by YukiGasai** [comment]
Use http for the 127.0.0.1
and https for the other url and it will work. Make sure to update both JavaScript Origin and Redirect URI.

**Comment by bhemmelgarn** [comment]
I'm not sure what changed exactly, but it just worked? I also have the Google Tasks plugin running, and I got finished getting the refresh token to mobile yesterday, maybe that is involved somehow? IDK. Sorry I can't identify the bug, but thank you for your persistence!
