### ISSUE TITLE
[Feature Request] Different icons for different views

### ISSUE THREAD

**Issue by mgorfer** [YukiGasai/obsidian-google-calendar#198]
I am not sure if this is maybe available somewhere.
I would like to have different default ions for the different calendar views. 

At the moment, all of my 6 Calendar Views look the same.
That is 
1. Calendar Web View
2. Calendar Year View
3. [Calendar](https://github.com/liamcain/obsidian-calendar-plugin)
4. Calendar Month View
5. Week View (calendar prefix missing)
6. Schedule View (calendar prefix missing)
7. Timeline View (calendar prefix missing).

It looks like this:
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/13124998/804e1fdc-b162-4ada-8b49-de455bd97ed0)

**Comment by YukiGasai** [comment]
Hi, I updated the icons.
You can use nearly every icon from [here](https://lucide.dev/icons/).
If you have some suggestions, let me know.

**Comment by mgorfer** [comment]
Awesome! The new icons are great!

And what is your comment on the items 5-7 in my list above missing the `Calendar` prefix?

**Comment by YukiGasai** [comment]
I updated all names to GCal … View.
This is a very minor change, so it will not get an own version.
I will close this issue for now.
