### ISSUE TITLE
Monthview and dashboard.css

### ISSUE THREAD

**Issue by rekkep** [YukiGasai/obsidian-google-calendar#199]
When the dashboard.css is active, the month of the gEvent gets renderd on top of the proberties.

<img width="1318" alt="Bildschirmfoto 2023-09-25 um 19 01 40" src="https://github.com/YukiGasai/obsidian-google-calendar/assets/52372226/c30ea835-7dce-49c0-94ea-d84c1e6242a5">

**Comment by rekkep** [comment]
have found the confict in the dasboard.css file:

```
/* Title at top of the document */
.dashboard .markdown-preview-section .title {
    top: 60px;
    position: absolute;
    font-size: 26pt !important;
    font-weight: bolder;
    letter-spacing: 8px;
}
```

when you mark this as comment or delet it, the month will show at the top of othe calender

**Comment by YukiGasai** [comment]
Hi, nice find.
The plugin does not change any of these classes and the month view is created using the [obsidian calendar ui](https://github.com/liamcain/obsidian-calendar-ui) library. 
I can't change this behavior, so I will close this issue.
