### ISSUE TITLE
no plugin options page

### ISSUE THREAD

**Issue by pastorjack** [YukiGasai/obsidian-google-calendar#2]
I just installed the latest version using BRAT. I'm using Obsidian insider build 0.15.9. There is no options page so I can't setup the plugin.

I have the Full Calendar plugin installed
![image](https://user-images.githubusercontent.com/121033/183460741-86a898fa-d1b2-4085-ac7c-0c73323cc171.png)

**Comment by YukiGasai** [comment]
Hi, thank you for testing. 

I think I found the problem. Please check out version [1.1.3](https://github.com/YukiGasai/obsidian-google-calendar/releases/tag/1.1.3)

**Comment by pastorjack** [comment]
thank you. I just got it setup and I'm starting to try out the options.
