### ISSUE TITLE
Attendees in Templates 

### ISSUE THREAD

**Issue by gte619n** [YukiGasai/obsidian-google-calendar#20]
In the Calendar API there is a list of attendees for each meeting. Is there a way to automatically add the attendees to the Notes template? I'd like to list the name as a link [[@Joe Smith]] for all attendees.

**Comment by YukiGasai** [comment]
Hi, I added a formatting for the array for now.
You should be able to write this `{{gEvent.attendees}}` to get the result.
- [[NameOne]]
- [[NameTwo]]
- ...

I will think about a better solution with more customformatting.

**Comment by gte619n** [comment]
So, I think I might be missing something on the template front, but in the event view, when I hit the Open/Create button, is there a way to link that to a template? It would also be nice if it would close the event modal and open the note.

**Comment by YukiGasai** [comment]
The template option in used for auto importing notes from google calendar, you have to include `:Uni/Math-obsidian-UniTemplate:` in the description of the event to make sure the plugin detects and inserts it into a new note.

In the example, `UniTemplate` is my template to use and `Uni/Math` is the folder where I want to save it to.

**Comment by gte619n** [comment]
Got it, and that works, but my issue is that I don't always know when I'll
need a meeting note. It would be great if I could just mash the button when
it's time.

Another idea would be to create a new note by a hotkey, based on whatever
calendar event is currently going on. That would be amazing!

**Comment by YukiGasai** [comment]
@gte619n your idea with the hotkey was fantastic. I added the button to the Detailpage of events and 2 new commands `Create Event Note` and `Create Event Note for current event`. 

Please test them for yourself. I hope it's intuitive enough.

**Comment by gte619n** [comment]
So I see the functions, but I can't seem to get them to work. When I select
the event, it prompts for a Template and Location every time, which slows
me down. It would be great if we could set defaults in the plugin settings
themselves. Also, when I select an event. No note is created. Am I doing
something wrong?

Thank you for such fast and great changes!

**Comment by YukiGasai** [comment]
Hi, 
I added a setting to use a default template and folder.

For better formatting, you can now use [Templater](https://github.com/SilentVoid13/Templater) with the exposed Api to allow for more freedom when using google event data in templates.

Here is an example

---------

\# Example Template
<%*
const {getEvent} = this.app.plugins.plugins["google-calendar"].api;
const theEvent = await getEvent("{{gEvent.id}}", "{{gEvent.parent.id}}");
const attendees = theEvent.attendees?.reduce((text,attendee) => text+= `- [[${attendee.email}]]\n`, "");

tR = `

Event Title: ${theEvent.summary}
Attendees: ${attendees}

`%>

Some footer text for the template

**Comment by YukiGasai** [comment]
The plugin will check for current events in the following order now.

Current time between start and end of event
If no event found
Current time between start - 1 hour and end of event
If no event found
Use full day events


Known problems. Event between two days, multi day events. 

I am also thinking about the concern of reoccurring events. Maybe a setting to add the current day to the file name to allow the creation of notes for each event.

**Comment by gte619n** [comment]
Very cool!! I will test tomorrow!!

**Comment by emciel** [comment]
Thanks for this useful plugin! I have a list-type property for attendees in my meeting event template, and I'd love to autopopulate it from the gCal event. 
Is it possible to format the attendees list for insertion in frontmatter? i.e. enclosed in quotation marks, like
- "[[name@company.com]]"
- "[[coworker@example.org]]"

This seems like an obvious use case. Am I missing something or is the gEvent.attendees output only intended for use in the body of the file currently?

**Comment by sandalsoft** [comment]
@emciel I have the same use case.  What tripped me up (until I found this thread) was that `gEvent.attendees` wasn't being processed like a list of objects, `JSON.parse('{{gEvent.attendees}}')` throws errors.  And this is because the `.attendees` property includes formatting. 

That said, the slightly modified code from above has me on the right track.

```
<%* 
const {getEvent} = this.app.plugins.plugins["google-calendar"].api;  
const theEvent = await getEvent("{{gEvent.id}}", "{{gEvent.parent.id}}");  
tR += '---\nattendees:\n';
const attendees = theEvent.attendees?.reduce((text,attendee) => {
	console.log(`attendee: ${JSON.stringify(attendee)}`)
	tR += `- ${attendee.email}\n`;
});
tR += `---\n\n`;
%>
```
