### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by joanwu95** [YukiGasai/obsidian-google-calendar#201]
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/49929713/eb344a2a-e924-4252-a150-fad566ebbb68)
there is an error when login

**Comment by YukiGasai** [comment]
Hi, please show me the confirmation of the Google cloud Project
Example:
![](https://user-images.githubusercontent.com/38146192/269669420-e3ddbf0c-7bea-4772-a299-fd26029ca897.png)

**Comment by joanwu95** [comment]
like this?
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/49929713/6431ff29-2eed-4837-b30b-b8d3fb27544d)

**Comment by YukiGasai** [comment]
Yes that's perfect.
You added an additional s to the 127.0.0.1 addresses.
The 127.0.0.1 Address should be http
Make sure to update the JavaScript Source and Redirect URL and it should work.

**Comment by joanwu95** [comment]
wow!!!
Thank you very much!!
