### ISSUE TITLE
Select End Date for "Full Day" entries. 

### ISSUE THREAD

**Issue by g1ronn1mo** [YukiGasai/obsidian-google-calendar#202]
Hello, 
it would be nice to have the opportunity to select the end day of a full day event. For now, only one day can be selected. 

![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/85943218/337d70aa-89d6-473f-9216-38852c86ce51)

Best Regards

**Comment by YukiGasai** [comment]
Hi,
I added an input for the end date of all day events.
Please test it yourself, you can close this issue if everything works as expected. ^^
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/38146192/3d2b85af-3ee7-4b07-892a-32b0ca9bbf8e)

**Comment by g1ronn1mo** [comment]
Did not expect it to be solved that fast, Good Job.
