### ISSUE TITLE
Calendar not showing in Obsidian

### ISSUE THREAD

**Issue by FrRacz** [YukiGasai/obsidian-google-calendar#204]
I've setup the OAuth-Client and have sucesfully authenticated myself (at least I got a message in my browser, that authentication was sucessfull and if I log out and in again it shows that Obsidian already has four different access rights.), but the plugin is not showing up in obsidian itself. Is there anything I am missing?

**Comment by YukiGasai** [comment]
If I understand correctly, you installed and enabled the plugin in obsidian and logged in with your own client. Have you tried using a command to open one of the views?
Example:
`Open gCal Timeline View`

**Comment by FrRacz** [comment]
It works perfectly lol. I just expected the calendar view to show up on the sidebar. Thanks for the nswer anyway. Awesome Plugin :))
