### ISSUE TITLE
Delete Event with Frontmatter

### ISSUE THREAD

**Issue by YukiGasai** [YukiGasai/obsidian-google-calendar#207]
### Discussed in https://github.com/YukiGasai/obsidian-google-calendar/discussions/206

<div type='discussions-op-text'>

<sup>Originally posted by **TimoWacke** October  1, 2023</sup>
I really really really do need 2 Way Sync :)

I understand that it is hard to build and not purpose of the plugin. Probably even harder to build in hindisight now?

But the create Calendar Event from Frontmatter function is sooooo Epic!!! It just needs an Delete Calendar EVent from Frontmatter function so that it allows for a 2 way sync workaround with the Commander Plugin</div>

**Comment by YukiGasai** [comment]
@TimoWacke I added the command `Delete gCal Event from Frontmatter`.
If the frontmatter contains an `event-id` it will get the event from Google and delete it.
If it is successful, the event-id is removed from the frontmatter.
I also added the feature, that the event-id is inserted if an event is created with the `Create gCal Event from Frontmatter`. The delete option should also work on all other event notes.

Please test it yourself and report problems here ^^

**Comment by TimoWacke** [comment]
holy shit that was fast! you're Awesome

**Comment by TimoWacke** [comment]
It works really well!
I think this is super powerful. I will tweak with Templatr and Commandr plugin a little bit to optimize the workflow a little bit and then I am looking forward to share it. I think that is the best part of your plugin..

**Comment by YukiGasai** [comment]
Sounds good, if you like you can add your examples to a documentation page.
If you use templater you can also use the [api](https://yukigasai.github.io/obsidian-google-calendar/#/Api/Overview).

**Comment by TimoWacke** [comment]
oh shit I think I knew only 1% about Templater :(( holy shit I need to learn that. I bet you have the best obsidian setup ever. I am just setting it up.
Have you shared it somewhere?
Should we move this discussion to somewhere else?

**Comment by YukiGasai** [comment]
TBO I have a very simple setup and only use a handful of plugins. I believe that a workflow should contain only a little bit of automation because the process of writing things down is a first step of doing them. For example, I pretty much only use the views from this plugin, but I want to help others achieve their desired workflow.
We can write on Discord if you like `@yukigasai` ^^
