### ISSUE TITLE
Date resets after changing one char

### ISSUE THREAD

**Issue by g1ronn1mo** [YukiGasai/obsidian-google-calendar#208]
When trying to insert a start or end day, the expected behaviour should be that when trying to upate one part of the date the other partes should stay the same and do not get reset. 

For now, the date gets resettet to tt-mm-jjjj  --:-- after edeting one part of the formular.

Best regards

**Comment by YukiGasai** [comment]
I was not able to figure out, why entering a `0` resets the complete input field, but I think I found a workaround. I also replaced the automatic date change with a check to make sure the start date is before the end date 
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/38146192/3db2c38a-3c4e-494c-9e12-8361435fe0c2)
Please test it yourself. You can close this issue if everything works as expected.

**Comment by g1ronn1mo** [comment]
Looks good to me.
