### ISSUE TITLE
Update by frontmatter

### ISSUE THREAD

**Issue by YukiGasai** [YukiGasai/obsidian-google-calendar#209]
Add option to update an existing Google Event with frontmatter.

**Comment by YukiGasai** [comment]
Hi @TimoWacke,
I added your idea for updating by frontmatter, please test it out.
You can close this issue if everything works as expected.
Disclaimer: Changing the calendar of an event is not possible with this option.

**Comment by TimoWacke** [comment]
Yes works well!
Would appreciate an update in the other direction very much but I understand that this is harder probably.

**Comment by YukiGasai** [comment]
Nice,
I will close this issue for now, as the bidirectional update is currently not planned.
