### ISSUE TITLE
How to format frontmatter using the properties function to create gCal event?

### ISSUE THREAD

**Issue by mentosweet** [YukiGasai/obsidian-google-calendar#214]
Hi,

I am having some issues trying to create an event using frontmatter with the new properties function.

Is there a certain way to format it? 

Thanks in advance!
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/137807059/6babdced-aaac-4fd3-b0bd-52ae6a3129d5)

**Comment by mentosweet** [comment]
Hi! thanks again!

Perhaps i do not have enough knowledge of the properties function introduced to obsidian.

Cant seem to do the mapping as well

**Comment by YukiGasai** [comment]
Okay you understand the concept, but your implementation is a little off.
The mapping is an object that contains the key value pairs.
Using the properties to set this up seems to be very complicated.
I would recommend to set up the mapping using frontmatter.
You can switch to frontmatter inside the obsidian settings.
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/38146192/04192052-813f-4ffd-9fbd-3db63eb74ea8)
The properties view is just some extra HTML on top of the frontmatter to allow a nicer User Experience, but it has its problems with objects.
