### ISSUE TITLE
Format time as 12-hour

### ISSUE THREAD

**Issue by jericjan** [YukiGasai/obsidian-google-calendar#216]
Hello, I noticed that times are displayed in military time, and I'm more used to 12-hour time. Unfortunately, there is no setting for that. I would love to see this implemented. Thanks!

**Comment by molTval** [comment]
`military time` or as it's called, normal time for everyone but the US of A

**Comment by YukiGasai** [comment]
Hi, in the timeline view you can click on the time to switch between the 24-hour and 12-hour format. In the schedule view you have to click on the name of the weekday.

![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/38146192/24aee42a-028e-4dae-8062-1a60f0b07a5c)

**Comment by jericjan** [comment]
Oh, I had no idea lol. I was expecting it to be somewhere in the settings. That's pretty intuitive, although not exactly obvious. Thanks tho!
