### ISSUE TITLE
Degraded Performance of Obsidian With Specific Views

### ISSUE THREAD

**Issue by rockman4311** [YukiGasai/obsidian-google-calendar#22]
Once Web View or Month View is opened, Obsidian begins to hitch and stutter. 

1. Scrolling becomes slower.
2. You can still type, but Obsidian will alternate between typing at normal speed and then freezing for a second or two - nothing typed will appear until after the hitch clears. This hitching appears to happen about every 5 seconds.
3. Interacting with menu items/glyphs has the same issue as typing - mostly fine but hitching every 5 seconds or so.

The issue does not occur with Timeline view or Schedule view, as far as I've seen. 

This began just before the release of 1.6. I first began using the plug-in when most of my calendars were on Apple Calendar, so there was very little info for the plug-in to parse. I then moved over to Google Calendar full-time and that seems to be what triggered the performance degradation. 

For now, I've been working around it by sticking to Timeline and Schedule view. Let me know if there's anything I can do to help diagnose the issue.

**Comment by YukiGasai** [comment]
Thanks for the feedback. For debugging, I need some more information.

Approximately how many events do you have per day?
Approximately how many events per month?
Do you use only the views?
Does the problem occur when using code blocks \`\`\`gEvent \`\`\`?

Could you test an [older plugin version](https://github.com/YukiGasai/obsidian-google-calendar/releases/tag/1.4.1) with the full Event load?

**Comment by rockman4311** [comment]
1. Today I have 9 events, which is typical. 
2. I have approx. 100-120 events estimated this month, across 5 calendars. I teach guitar lessons, which means I have an individual event per student.
3. I frequently leave Obsidian's file explorer + a note open on the left hand side, with a timeline view open on the right hand side plus calendar view open above the Tags/Outgoing links. 
4a. Yes, it does. I tried day view and web view in the code block with no issue, but as soon as I tried month view, the hitching returned.

5. Sure! I'll also try 1.6.4 and see what that does. 

Thanks so much! Loving the plug-in.

**Comment by rockman4311** [comment]
1. 1.4.1 was no different, unfortunately.
2. With my normal set-up (schedule view + month view), 1.6.4 is better. Still sluggish, but no hitching. Unfortunately, 1.6.4 introduced another significant issue: days showing up out of order on schedule view. I added a new issue to the GitHub page.

**Comment by YukiGasai** [comment]
Hi @rockman4311,
I think I found and fixed a mistake causing major performance problems. Could you please test with the latest version and check if the usability is better now?

**Comment by rockman4311** [comment]
Hi there! So sorry for the delayed response (life got very busy). Good news is performance is SO much better now. I've been using Obsidian and your plug-in without even really thinking about it. 

Thanks so much!

**Comment by YukiGasai** [comment]
Cool, that's how it should be.
I will close this issue now. If problems reappear, please open a new issue.
