### ISSUE TITLE
Hide certain calendars in views?

### ISSUE THREAD

**Issue by jkbhagatio** [YukiGasai/obsidian-google-calendar#226]
Hi, is it possible to hide certain calendars in views? In my usecase, I have many shared calendars linked to my google account, but I would ideally be able to do something like toggle which calendars display in the plugin's views.

**Comment by YukiGasai** [comment]
You can remove calendars intiarly by adding them to the blacklist in the settings or remove them individully by adding them to the exclude setting in the view options. https://yukigasai.github.io/obsidian-google-calendar/Views/Settings/ExcludeSetting

**Comment by jkbhagatio** [comment]
Ah cheers, I hadn't seen `exclude`. Thanks for the quick response and the great plugin!
