### ISSUE TITLE
Days Showing Out of Order In Schedule View

### ISSUE THREAD

**Issue by rockman4311** [YukiGasai/obsidian-google-calendar#23]
Release 1.6.4

In Schedule View, my days are showing up like this. 

Nov. 6
Nov. 8
Nov. 2 (today)
Nov. 9
Nov. 3
Nov. 4
Nov. 5
Nov. 7

This occurs both in a GCal code block and by hotkey.

**Comment by YukiGasai** [comment]
I will close this issue for now. If the problem reoccurs, we can open it again.
