### ISSUE TITLE
How this plugin works?

### ISSUE THREAD

**Issue by DDosos** [YukiGasai/obsidian-google-calendar#236]
Hello! It is completely unclear how this plugin works. I installed it, followed the setup instructions, allowed access to the google calendar, logged in. And then what? ))
1) Where? How do I see the list of tasks and events? There is Obsidian inside.
2) How to add tasks, how to change them?
3) Is there a How To on the main tasks that this plugin solves?

Thank you in advance and thank you for your hard work!

**Comment by brandon-is-a-coder** [comment]
https://yukigasai.github.io/obsidian-google-calendar/

**Comment by Medullitus** [comment]
Not working
