### ISSUE TITLE
[Feature Request]: Filter events

### ISSUE THREAD

**Issue by aseyedia** [YukiGasai/obsidian-google-calendar#238]
It would be cool if there was a way to natively filter events with this plugin. I have a calendar feed for school that lumps together TA office hours with assignment due dates. I wish there was a way to bring in only the assignment due dates without any of the TA office hours. I'm not experienced with svelte or TS but that is something I have also considered looking into contributing as a feature.

**Comment by YukiGasai** [comment]
Please try out this option
![image](https://github.com/YukiGasai/obsidian-google-calendar/assets/38146192/cbfdf9d0-3951-4a3c-b01f-a7b1b73faee1)
https://yukigasai.github.io/obsidian-google-calendar/Settings/IgnorePatternList
