### ISSUE TITLE
Incorrect Tool Tip on Schedule View

### ISSUE THREAD

**Issue by gte619n** [YukiGasai/obsidian-google-calendar#24]
When I use the command palette to open the Schedule View, the tool tip says "Calendar Month View"

<img width="379" alt="image" src="https://user-images.githubusercontent.com/223900/199607284-62090e0d-8f25-4c2a-8793-df3ad1fd7717.png">

**Comment by YukiGasai** [comment]
Nice found I will change it with the next update 👍🏻
