### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by AMGMNPLK** [YukiGasai/obsidian-google-calendar#25]
![image](https://user-images.githubusercontent.com/19272675/200196038-caa3a425-e8fa-4967-bb90-c09edc345b52.png)

After following the steps I get this errors when click on the login button in the plugin

**Comment by YukiGasai** [comment]
Please restart obsidian and try again.

**Comment by AMGMNPLK** [comment]
I did it a few times.

**Comment by YukiGasai** [comment]
Hi, thank you for trying to create your own client. 

This error is a known problem. To authenticate with google the plugin will start a local server. The port for this server is 42813. If the server is started twice, by for example clicking the login button twice, the port will already be in us, and you get this error.
Normally, this port should not be in use when not trying to login, but you could test this before trying to log in.

CMD: `netstat -ano -p tcp |find "42813"`

If this still doesn't help, I need some extra information to debug this issue.
What OS are you using?
What version of obsidian are you using?
Are you using the latest plugin version?
Have you any special firewall setting?

**Comment by YukiGasai** [comment]
Closed due to inactivity
