### ISSUE TITLE
Placeholders for event note title not working correctly

### ISSUE THREAD

**Issue by lilyofthealley** [YukiGasai/obsidian-google-calendar#251]
I've tried to use {{event-hour}}, {{event-hour24}} and {{event-minute}} to create event notes that have the starting time of the event in the title but they are not parsed and my titles actually were, for example:
'04-12 {{event-hour24}}.{{event-minute}} Title'.

**Comment by lilyofthealley** [comment]
Solved the issue.
In the documentation the placeholder for the start hour and minute are reported to be {{event-hour}}, {{event-hour24}} and {{event-minute}} while in the source code {{event-start-hour}} {{event-start-hour24}} and {{event-start-minute}} are used

**Comment by YukiGasai** [comment]
Hi,
thank you for pointing this out.
I updated the docs.
