### ISSUE TITLE
Missing Frontmatter Commands

### ISSUE THREAD

**Issue by eddiewastaken** [YukiGasai/obsidian-google-calendar#265]
I can't find the commands mentioned [here](https://yukigasai.github.io/obsidian-google-calendar/EventNotes/FrontmatterActions), specifically **Create gCal Event from Frontmatter**, **Update gCal Event from Frontmatter** and **Delete gCal Event from Frontmatter**.

These are all the commands listed for this plugin by the Command Palette:

![image](https://github.com/user-attachments/assets/ec2449dd-65d7-4d53-9579-eabbd2af7839)

I couldn't find anything referenced in the plugin settings, either. Am I missing something?

Thanks!

**Comment by YukiGasai** [comment]
Hi,
the commands will only show up if you have a note open and focused.
