### ISSUE TITLE
Unable to load when opening vault

### ISSUE THREAD

**Issue by dodo-the-dev** [YukiGasai/obsidian-google-calendar#27]
Just updated the plugin and whenever you relaunch the vault, it fails and disables itself. I also can't access the settings pane, even when app is enabled.

OS: Windows 10 pro
Obsidian version: 1.0.3
Plugin version: 1.6.11

**Comment by m-paul** [comment]
Same thing is happening for me

**Comment by YukiGasai** [comment]
Hi,
thank you for bringing that to attention. 
I think I found the problem and fixed it with the latest version 1.6.12 
When updating, the error will occur one more time, but should not return after that.

I would be cool if you could test it one more time and if the bug is not fixed give a detailed description to reproduce the error.

**Comment by dodo-the-dev** [comment]
Good morning,

Yes, the update works well done and thank you.

**Comment by dodo-the-dev** [comment]
UPDATE:
It does now work, but needs to be reinitiated each time you open the app (it still says "unable to load Google Calendar" when opening the app, but when turned on, the `gEvent` blocks do work, but not automatically from opening Obsidian.

**Comment by matthewturk** [comment]
I'm getting this error on startup in the developer console with the current version of the plugin:

```javascript
Plugin failure: google-calendar Error: Failed to find daily notes folder
    at Uq (VM906 plugin:google-calendar:75:30875)
    at anonymous (VM906 plugin:google-calendar:85:17776)
    at e.<anonymous> (app.js:1:1035228)
    at app.js:1:235201
    at Object.next (app.js:1:235306)
    at a (app.js:1:234045)
```

If I turn on the plugin manually after that, all the blocks show "`LOADING`" but this error shows up in the console:

```
Uncaught (in promise) Error: Request failed, status 400
    at new t (app.js:1:699319)
    at Xb (app.js:1:699511)
    at app.js:1:700188
    at app.js:1:235201
    at Object.next (app.js:1:235306)
    at a (app.js:1:234045)
```

with and expanded traceback pointing at:

```
  | g | @ | plugin:google-calendar:75
  | eval | @ | plugin:google-calendar:75
  | bS | @ | plugin:google-calendar:75
  | h | @ | plugin:google-calendar:90
```

**Comment by YukiGasai** [comment]
@matthewturk thank you for the details. 
I think I fixed at least the problem with the missing daily notes folder. If you have time, please test the latest version.

**Comment by matthewturk** [comment]
@YukiGasai That did fix it for me!  I'm now getting the HTTP 400 errors, but I will try a few things before reporting a new issue.  Thank you so much for your attention on this.

**Comment by YukiGasai** [comment]
I think this issue has been resolved for everyone.
