### ISSUE TITLE
HTTP 400 errors on loading

### ISSUE THREAD

**Issue by wbthomason** [YukiGasai/obsidian-google-calendar#29]
First off, thanks for the excellent plugin! I've enjoyed it.

I'm currently unable to load any calendar views, whereas this previously worked as expected. In the developer console, I get a large number of these errors 
```js
Uncaught (in promise) Error: Request failed, status 400
    at new t (app.js:1:699319)
    at Xb (app.js:1:699511)
    at app.js:1:700188
    at app.js:1:235201
    at Object.next (app.js:1:235306)
    at a (app.js:1:234045)
```
which, given @matthewturk's comment in https://github.com/YukiGasai/obsidian-google-calendar/issues/27#issuecomment-1323423822, I believe to be the source of the failure to load.

I'm happy to provide more information, etc. - just let me know what would be useful. Thanks!

**Comment by YukiGasai** [comment]
Hi, thank you for confirming this as a problem.

Have you tried login out and in?
Are you using an own OAuth client or the test client?

**Comment by wbthomason** [comment]
I'm using my own OAuth client. I've tried disabling and enabling; will give logging in and out a go once I'm back at my computer (I hadn't tried this yet because I'm afraid that will make me lose my Blacklist of calendars, which is fairly long)

**Comment by dhniceday** [comment]
I have the same issue (error) since the previous update. 
After removing my credentials, loggin out, putting my credentials back and loggin in, i have the following error: Google Calendar: missing settings or not loged in.

And indeed, in the settings I don't see my calendars. It seemed I am not logged in, even when the authentification said successful. I could repeat the login process multiple times with the same negativ result. No events are retrieved.

**Comment by YukiGasai** [comment]
Hi @dhniceday,
please make sure there are no spaces at the end or the beginning of the client secret.
Could you also check the developer console CTRL + SHIFT + I for any error messages?

**Comment by dhniceday** [comment]
Empty space at the beginning of my client secret. That's it.... 
happens even to the best, right :)

Many thanks !

**Comment by YukiGasai** [comment]
Can happen to everyone, I added a trim to the secret to remove leading and trailing white space. 
@wbthomason could you check if this is your problem as well, so we can possibly close this issue?

If whitespaces are not the issue, you can turn on debug mode in the settings to get more feedback in the console.

**Comment by wbthomason** [comment]
@YukiGasai Sorry for the delay! I did not have whitespaces, but logging out and logging back in has, at least for now, fixed the problem for me. I'll close the issue and re-open if it returns, with a report from debug mode. Thanks!
