### ISSUE TITLE
No option to set the default start day

### ISSUE THREAD

**Issue by mustarde** [YukiGasai/obsidian-google-calendar#31]
Thank you for the plugin! It's the only Google calendar that I found to be working bidirectionally.

There is no option to choose Monday as the first day of week.

**Comment by YukiGasai** [comment]
Hi @mustarde, 

I know this is only a workaround, but you can install the [calendar](https://github.com/liamcain/obsidian-calendar-plugin) plugin.
The month view of the Google calendar is based on this plugin, so when you update the settings of the calendar plugin, the month view of the Google calendar plugin should update as well.

I will add this to the todo list as well.

**Comment by YukiGasai** [comment]
Hi, 
I have some bad news.
When updating the calendar ui to set the weekStart property, the dependencies go wild and destroy the plugin in different places. Not allowing to use periodic notes for example, so for now the best option, in my opinion, is to set it by the calendar plugin itself.
