### ISSUE TITLE
Better Recurring Events

### ISSUE THREAD

**Issue by YukiGasai** [YukiGasai/obsidian-google-calendar#33]
## Recurring Events

The current UI to create recurring events is based on fixed-intervals. It is unable to support things like "every month on second friday" or "every year on the third last wednesday", etc. I think it would make more sense that for the purpose of event from note, we support the [RFC5545](https://www.rfc-editor.org/rfc/rfc5545) which I believe is what is used by the Google Calendar API.

However, typing out RFC5545 recurrence rule is incredibly cumbersome. So my suggestion is that you use something like the  [Rrule node module](https://github.com/jakubroztocil/rrule) which is also used by Obsidian Task plugin. You can let the user put in a string like "every month on second friday", throw the [start date, user text, end date] to `RRule.fromText()`, and convert it into RFC5545 format using `RRule.toString()`. Viola, you can now pass this to Google API.

The work for this might be worth another issue though, it also paves the way to better recurrence support for the UI too.

_Originally posted by @CovetingEpiphany2152 in https://github.com/YukiGasai/obsidian-google-calendar/issues/30#issuecomment-1351349598_

**Comment by YukiGasai** [comment]
Hey @CovetingEpiphany2152, 
I added a first test for the recurrence field. Just add recurrence as field to the frontmatter with the desired text.

---

Example 
~~~
---
start:
 date: 12/24/2022
end:
 date: 12/24/2022
description: file
calendar: Leben <- Use your own calendar
recurrence: every monday
---
~~~

The example should
- create an event named after the note
- the description should contain the complete note as HTML (Except images)
- the event will happen at the start date until the end date and will then repeat every monday

---

This was a great idea. I really like the functionality, but I can already see a lot of inconsistancies appearing. If you have some spare time please check it out yourself.

**Comment by CovetingEpiphany2152** [comment]
Hi @YukiGasai , it works perfectly! I've tested a few use case and can't find any issues.

Btw, if anyone is wondering, the recurrence text itself has the ability to specify when the recurrence ends through the (until and for keywords). For example,

`everyday until dec 29 2022`, `every week for 3 times`.

**Comment by CovetingEpiphany2152** [comment]
Okay, I have found a bug, but it's not you, it's rrule 😂. `RRule.fromText()` has an off-by-one error where the "until" date is excluded instead of included. I went looking for it in RRule repo, and guess what? Obsidian task dev has already filed this issue a year ago. I left a comment on the root cause:

https://github.com/jakubroztocil/rrule/issues/486

**Comment by YukiGasai** [comment]
I added the reoccurring text in the frontmatter and event detail view. To test the text, check out [this](https://jakubroztocil.github.io/rrule/) page.
I will close this issue for now.
