### ISSUE TITLE
Better Event Description (Create Event from Frontmatter)

### ISSUE THREAD

**Issue by YukiGasai** [YukiGasai/obsidian-google-calendar#34]
## Event Description

Currently, the event created with command creates an event with no description. I think we can choose one of the following to populate the description with.

- let the user specify a string, which is a header. all content from that header onwards will be copied for the event description
- let the user specify an array of strings, each for a header. the headers and contents nested within those headers will be copied for the event description

Headers can be searched with `/#+\s+(header string)/` regex.

_Originally posted by @CovetingEpiphany2152 in https://github.com/YukiGasai/obsidian-google-calendar/issues/30#issuecomment-1351349598_

**Comment by YukiGasai** [comment]
I don't really understand this suggestion.

You can set the field `description` in the frontmatter to add text to the event description.

I can imagine a special value to copy the header or the entire file into the description.
Example

To set the description to a normal text
~~~
---
description: Meeting is important for me
---
~~~

To copy the headers of the file
~~~
---
description: Headers
---
~~~

To copy the entire file
~~~
---
description: File
---
~~~

**Comment by CovetingEpiphany2152** [comment]
Ah sorry, my initials description was not clear. I think your suggestion makes a lot of sense. For my use case, I only want to copy part of my file for the description, instead of the whole file. Hence the suggestion is to copy all content after a specific header, or to copy nested content from all listed headers.

**Comment by YukiGasai** [comment]
Hey, 
I added an option, that should help you with your usecase.
You can now add a list of zero based indexes into the `description` field.
The indexes are for the headers of sections you want to export content from.
Every header has its own index, the level of the header h1, h2 .. is ignored.
Example
~~~
---
description: [1,4]
---
~~~

In this example, all text between header 1 and 2 as well as header 4 and 5 is exported into the event description

**Comment by CovetingEpiphany2152** [comment]
Hi thanks for working on this, can I suggest that the index works with negative integers as well? For example, -1 for last header, -2 for second last header, etc.

**Comment by YukiGasai** [comment]
Hi @CovetingEpiphany2152 ,
I added the option to use negetive number, addionaly I added the option to define a range to import the headers:
Example

~~~
description: [0,-1,[4,9]]
~~~

This will import the first, last and 4.,5.,6.,7.,8.,9. Headers with their content.
Negative numbers in the range should work, but I didn't test them that much.  :)
