### ISSUE TITLE
Create/open daily note in same tab

### ISSUE THREAD

**Issue by novakwh** [YukiGasai/obsidian-google-calendar#35]
Hi, when using the monthly calendar sidebar to open a daily note, it opens (or creates) in a new tab -- I wind up with a whole bunch of open tabs (in some cases multiple tabs of the same document) which is not the way I like to work. Can it be set so that you open  or create a daily note in the currently open tab? (This is how the standard calendar plugin works.) Thank you!

**Comment by YukiGasai** [comment]
Hi @novakwh, 
the daily notes should now open in the current editor tab.
Please test it yourself and close the issue if it works as expected.

**Comment by novakwh** [comment]
Yes, this works, thank you so much!
