### ISSUE TITLE
Trojan in the new plugin? 

### ISSUE THREAD

**Issue by Sriramgireesh** [YukiGasai/obsidian-google-calendar#36]
![image](https://user-images.githubusercontent.com/66196487/209083338-92b7706c-790f-49ca-97ce-84a84580bf71.png)

Could you please look into this? Is this a safety issue?

**Comment by YukiGasai** [comment]
Hi @Sriramgireesh ,
I don't really believe this to be true. With the latest update I only added Parsing of frontmatter.
For savety I will roll back to version 1.7.6 and get in touch with the obsidian devs.

**Comment by joethei** [comment]
Hi, Obsidian team here.

This is a false positive by the antivirus used.
This is caused by a library used in one of the dependencies.

There is no Trojan included in release 1.7.7.

Here is the original issue: https://github.com/jensyt/imurmurhash-js/issues/1
