### ISSUE TITLE
Restricted "day" view

### ISSUE THREAD

**Issue by matthewturk** [YukiGasai/obsidian-google-calendar#38]
Hi!  Would it be possible to have my "day" view restricted to only N hours, with a default view, perhaps including times as well as hour counts.

**Comment by YukiGasai** [comment]
Hi, could you go a little more into detail with this idea.

If I understand you correctly, you want to limit the hours in a day to a specific range, let's say from 7am to 3pm.

Does this have to be an option for the view, or would it be enough to add this to the options in the gEvent code block to embed the view in a file?
Should events that started or end outside the range be included?
Should the view get smaller or be zoomed in?

**Comment by matthewturk** [comment]
@YukiGasai these are all great questions -- I should have been more explicit in my initial query!

I was hoping to limit the displayed hours to a range, such as (as you suggest) 7am to 3pm.  It would be absolutely great to have this be an argument to the `gEvent` code block.

For starting inside or outside, that's a good question and one I'm not sure I have the right answer to.  My inclination is that they should not be included, because that simplifies (for instance) multi-day events that may overlap and that would present a confusing view.

I also think it would be beneficial to have the view be smaller, rather than zoomed in, as that would allow the system to be embedded more easily and with more fixed usage of screen space.

Do you think this is something I could help trying to implement?

**Comment by YukiGasai** [comment]
Hi @matthewturk,
I added the feature, but it will just cut off at the selected hours. This made it easier to program because I only had to add CSS instead of changing the entire display function. I hope this still works for you. 

The option is called hourRange and takes in an array of 2 number, the start and end hour.

Example:
~~~
```gEvent
date: 2023-01-14
type: day
hourRange: [3,13]
```
~~~
