### ISSUE TITLE
AM/PM or momentjs formatting for time in day view

### ISSUE THREAD

**Issue by matthewturk** [YukiGasai/obsidian-google-calendar#39]
In day view, the hours are listed as 0 .. 23.  It would be nice to be able to either supply a momentjs-style format string in the `gEvent` code block or to have AM/PM as an option.

![image](https://user-images.githubusercontent.com/89019/210766942-0e65da1b-7613-47a1-be8a-015dc6560497.png)

**Comment by YukiGasai** [comment]
Hi @matthewturk,
first of all thank you for your donation <3.

I added the option to click on the hour text to switch between 24 and 12 hour format. 
The setting will be saved and synced with all day views.

**Comment by matthewturk** [comment]
Thank you!  I love it!
