### ISSUE TITLE
Feature Request: Automatically insert events for today into daily note

### ISSUE THREAD

**Issue by pastorjack** [YukiGasai/obsidian-google-calendar#4]
Loading today's events using a code block when creating a new daily note would be awesome.

A similar use would be loading events for a weekly note.

**Comment by YukiGasai** [comment]
To achieve this, you can just insert the code block into the daily note template like this:

```
    ```gEvent
        date:{{date}}
        type:day
    ```
```
This will keep the date, so if the date rolls over after creating the note it will keep its original date


Or if you want to see the today's notes in older daily notes, you can use today

```
    ```gEvent
        date:today
        type:day
    ```
```

For the weekly note I would use the month view to see all events in the week
```
    ```gEvent
        date:{{date}}
        type:month
    ```
```


If that's not want you meant, I need more explanation please.

**Comment by pastorjack** [comment]
I was thinking something different, but the more I think about it I have a better idea.
Could you add schedule to the types?
    ```gEvent
        date:{{date}}
        type:schedule
    ```
It would be an added bonus if when clicking on the event, I could edit it inside obsidian in a modal instead of going to the website.

**Comment by YukiGasai** [comment]
Can you give more details about the content of the schedule, it sounds like the `type:day` (timeline) type

**Comment by pastorjack** [comment]
It would correspond to the "Schedule" web view on Google Calendar: ![image](https://user-images.githubusercontent.com/121033/185762301-b76047b4-0910-40d2-b467-f86d66792ff3.png)

It is just a list of events without the empty spots on the day view. Ideally, you could show a list of events for a day or a specified period of days

**Comment by YukiGasai** [comment]
I added the view. Really nice idea, I didn't even know about this feature from Google calendar ^^

You can set the start date with `date: {{date}}` and the timespan it displays with `timespan: {{numberOfDays}}` default is 4 but I may change it to 7

**Comment by pastorjack** [comment]
I like it! I need to do some CSS work to get it to fit into my theme better. 

I do have a problem with it reloading every 10-15 seconds

**Comment by YukiGasai** [comment]
I fixed the loading problem. I also changed some CSS and elements around, but I hope it doesn't interfere too much. If you have any good ideas to make the layout more responsive, feel free to contribute with a pull request.

**Comment by pastorjack** [comment]
Thank you! I'll work on styling it the way I like over the next couple of days.
