### ISSUE TITLE
Setting dynamic path in event information

### ISSUE THREAD

**Issue by achew22** [YukiGasai/obsidian-google-calendar#42]
In the documentation it says:

> Google events that contain :obsidian: inside the description will create new notes if the plugin starts

This works great when the description of my event is

```
:daily/2023/01/2023-01-11-obsidian-templates/meeting:
```

but when I try to make it dynamic it doesn't seem to work:

```
:daily/{{date}}-obsidian-templates/meeting:
```

I get an error. Do you have any suggestions on how I can automatically make events appear in the correct date base directory?

**Comment by YukiGasai** [comment]
Hi @achew22,
it would be possible to achieve this by using templater and using a template that moves the file into the folder you want. 
But to make things easier, I just added the option to use templates in the description.

You can now use 
`{{date}}` to insert today's date
`{{event-date}}` to insert the event's start date
`{{event-title}}` to insert the events title
