### ISSUE TITLE
Feature Request: Add Regional options for Month View and the @ syntax

### ISSUE THREAD

**Issue by preslavnpetrov** [YukiGasai/obsidian-google-calendar#44]
Right now I'm in the UK, but the month view is showing the beginning of the week as a Sunday, which is very confusing for me as I'm used to seeing the week begin on monday.

Additionally, when trying to reference a date with @12-01-2023, it will reference 01 December 2023, rather than 12 January 2023.

Could we maybe get some options to set the specific regional format we want to use?

Thanks

**Comment by YukiGasai** [comment]
Hi @preslavnpetrov, for your problem with the month view and the default start day, please take a look here #31. There is a workaround.
For the @ annotation, I will take a look.

**Comment by YukiGasai** [comment]
Hi @preslavnpetrov,
I added an option to enable/disable the at annotation completely.
If the option is enabled, you can select the preferred date format.

The solution I used is no ideal, but there are some problems with moment.js the selection of the local.

Please test it yourself and close the issue if everything works as expected.

**Comment by preslavnpetrov** [comment]
Works great, wonderful work. Closing this now.
