### ISSUE TITLE
Having multiple event notes of the same name confuses the "Open Event Note" option in event view

### ISSUE THREAD

**Issue by preslavnpetrov** [YukiGasai/obsidian-google-calendar#45]
Repro steps:

Create two google calendar events on two different days, say 1 January 2023 and 2 January 2023,
Call both "Test Event"
In Obsidian Month View, open the event on the 1st January
Click "Create Event Note"
Observe, the note is created as expected
In Obsidian Month View, open the event on the 2nd January
Observe, the button says "Open Event Note", even though no event note has actually been created for it.

This seems like a case of the plugin looking at the note names and event names to map them, and not at their note and event ids respectively.

Would be nice to fix this for recurring events that need unique notes for the different days they happen on.

Thanks!

**Comment by YukiGasai** [comment]
Hi @preslavnpetrov,
the main problem here is that the file name of the note is the event title, but every filename can only exist once. 
I could imagine adding a date to the end of the filename if there already is a note with the same title.
Do you have an idea how to link a file to an event in a good, hidden way? Maybe frontmatter?

**Comment by preslavnpetrov** [comment]
Hey!

Yeah I would go about it by first trying to match a google event ID with a frontmatter key, like "event-id", then fall back to matching by title. That way, you can keep backwards compat for people who arent using that functionality, but anyone who's using it in the future can just create a template with frontmatter like this:

---
event-id: {{gEvent.id}}
.
. *other frontmatter*
.
---

**Comment by YukiGasai** [comment]
But should the function insert the event-id automatically, independent of what template is being used?

**Comment by preslavnpetrov** [comment]
I believe that would cause complications with other templating engines like Templater. Results like this:

```
---
event-id: *templated id here*
---
---
*other templating engine's inserted template*
---
```

 Better to keep this as an opt in feature for the time being.

Alternatively, the same mapping can be done with a json file stored in the .obsidian directory, that stores note ids as keys and event ids as values, or vice versa. This would probably take significantly more dev work though, as you will have to manually clear entries when changes occur, like an event or a note being deleted.

**Comment by MaciejWieczor** [comment]
Maybe it could be handled how it is in the "full calendar" plugin? You can type path where to save new notes, and the path can have variables like month, day, year as folders or name. Here maybe it could come out of the gEvent.start.date?

**Comment by preslavnpetrov** [comment]
Yeah periodic notes also handles it that way, could be a good idea.

**Comment by YukiGasai** [comment]
@MaciejWieczor this is already possible as requested in #42. 
I will also create a popup if the file that is being generated already exists, so you can change the path accordingly.

The main problem is to map the notes to the events. I will go with the frontmatter approach for now.

**Comment by YukiGasai** [comment]
Please check out version 1.8.0.
I added the frontmatter check and when creating a note with the plugin it will add the event ID automatically.
Plus, if you create a note that already exists, the Module to select a template and path will open to change the path 


There are basically 2 types of event notes now
Old without event ID
New with event ID

The new is always preferred, but when only opening a note, the old note will be used as fallback.
In the EventDetailsView there are 3 Buttons. If the event has an old note, you can create a new event Note for each reoccurring event if you want to.

I hope backwards comp is still there. Maybe you have better ideas for the EventDetailsView Buttons. 

Perhaps the option to add prepend the date would be helpful for people without this folder structures.


If you have some time, please test it yourself. I hope I didn't destroy anything ^^


To fix the problem with the duplicate name, you can simply set the default folder with a variable
### Options
 - `{{date}}`
 - `{{event-date}}`
 - `{{event-title}}`
 - `{{date-day}}`
 - `{{date-month}}`
 - `{{date-year}}`
 - `{{event-day}}`
 - `{{event-month}}`
 - `{{event-year}}`
 
### Example
![grafik](https://user-images.githubusercontent.com/38146192/213333554-3dd93550-2bfb-4afd-be5f-65ee5977215c.png)

**Comment by MaciejWieczor** [comment]
@YukiGasai works great <3
thank you :)

**Comment by preslavnpetrov** [comment]
It works perfectly, well done! Really appreciate your work.
