### ISSUE TITLE
Calendar Month View - monday as first day of the week 

### ISSUE THREAD

**Issue by MaciejWieczor** [YukiGasai/obsidian-google-calendar#47]
I wanted to use calendar month view in the sidebard as a way to access notes tied to those in the prettier web view in the main window. 
But I have monday as the first day in the web view (as this is the norm where I live) and sunday in the sidebard month view. Is there some way to change the calendar month view first day of the week?
Or maybe there is some better way of accessing notes tied to events in the calendar?

**Comment by MaciejWieczor** [comment]
I have no idea why but it fixed itself on its own after like an hour

**Comment by YukiGasai** [comment]
Hi @MaciejWieczor,
I hope it keeps working for you, but if it doesn't, take a look here #31.

**Comment by MaciejWieczor** [comment]
Thanks, it actually started working for me because I installed it to test some other stuff :b
I was wondering (because I didn't find a githube issue on the topic), is it just me or is it the design that when I create new note for some event I have to close the event window and only then I can jump to the newly created note? I was wondering if I can create a note and just go to it without reopening the event window
