### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by joniac1** [YukiGasai/obsidian-google-calendar#49]
When I put my mail address and my password, I get this message : 

Error 401: disabled_client
Sign in with Google temporarily disabled for this app. This app has not been verified yet by Google in order to use Google Sign In.
[Learn more](https://support.google.com/cloud/answer/7454865)
Request Details
The content in this section has been provided by the app developer. This content has not been reviewed or verified by Google.
If you’re the app developer, make sure that these request details comply with Google policies.
access_type: offline
response_type: code
redirect_uri: https://obsidian-google-calendar.vercel.app/api/google/callback
prompt: consent
client_id: 783376961232-v90b17gr1mj1s2mnmdauvkp77u6htpke.apps.googleusercontent.com
scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/calendar openid

**Comment by YukiGasai** [comment]
This is because the public client is full.
Please use your own client for now. 
[Here](https://yukigasai.github.io/obsidian-google-calendar/#/Basics/Installation) is a guide on how to set it up.
