### ISSUE TITLE
Trying to understand Auto create Notes from Events

### ISSUE THREAD

**Issue by pastorjack** [YukiGasai/obsidian-google-calendar#5]
I can successfully create the note without a template. When trying to use a template, I always get a message that the template cannot be found. 

To use a template, you need to add the name of the template to the gCal description. It would be great if you could set a default template in the settings and override it on an individual basis.

Event data that can be imported is unclear. How can I insert those details into my template?

An option to choose a location for the newly created file would be helpful.

How can I find the note created in Obsidian from viewing the gCal event? It would be nice to have a link (the Full Calendar plugin does this nicely).

Thanks so much for making this plugin. I've enjoyed testing it out and can see how it will be super useful as you continue to develop it.

**Comment by pastorjack** [comment]
One more thing :)
Could you make a command to import events so that we don't have to close and reopen Obsidian?
Thanks!

**Comment by YukiGasai** [comment]
### Changes

I added the command `Google Calendar Trigger Auto Import` to check the events again.

There is now a button `Open/Create` in the Details View to create and open a note from an event. A new note can be created without the specific text :obsidian: in the description.

![grafik](https://user-images.githubusercontent.com/38146192/183944060-296ccada-a9e2-4554-aeac-0b2d975a40b0.png)

### Templates
To use a template, make sure the description contains :obsidian-TemplateName: also check if you have enabled the plugin for the template and the template is inside the templates folder. If all of this checks out, I need more information to debug the issue. 

The general syntax for the description is :Optional/Folder/Name-obsidian-OptionalPluginName:

The option to insert Event details into the plugin is currently not supported but I have a look at it. It seems like a very usefull feature.

**Comment by YukiGasai** [comment]
With version 1.1.5 you can now add extra template strings in the template file to insert event information into the event note like this.

`{{gEvent.id}}` or for templater `<%gEvent.organizer.email%>`

The list of possible fields is in the [Google Calendar Documentation](https://developers.google.com/calendar/api/v3/reference/events)

**Comment by pastorjack** [comment]
I'm still trying to get this to work. I'm using 1.1.8 of your plugin. Obsidian version 0.15.9.

I can get it to create a note in a specific folder but it says the template is invalid.
This is the description in my test calendar event:
`:Planning/Events-obsidian-gcal-events:`
The event note is correctly created in the folder `Planning/Events` but it does not use the template.
My template file is `Resources/templates/gcal-events`
The template folder is set correctly in the core plugin settings.
Here are it's contents:
`---
title: {{gEvent.summary}}
allDay: false
startTime: {{gEvent.start.dateTime}}
endTime: {{gEvent.end.dateTime}}
date: {{gEvent.start.date}}
---
# {{gEvent.summary}}
Description:: {{gEvent.description}}
Location:: {{gEvent.location}}

[{{gEvent.attachments.title}}]({{gEvent.attachments.fileUrl}})
{{gEvent.hangoutLink}}

[Edit]({{gEvent.htmlLink}})`

**Comment by YukiGasai** [comment]
I recreated your setup in a test vault. The template was inserted, but the custom template strings were not replaced. I hope I fixed it with the new version.

To access items from a list, you have to use `{{gEvent.attachments[0].title}}`

If it still doesn't work, please check the dev console for any errors.

**Comment by pastorjack** [comment]
This works as expected now! Thank you so much for your work!
