### ISSUE TITLE
iOS Failed To Load Plugin

### ISSUE THREAD

**Issue by joshwent** [YukiGasai/obsidian-google-calendar#50]
Getting `Failed to load plugin google-calendar` error when opening Obsidian on iOS.

This error happens whether the plugin was initially installed on iOS or MacOS. The error also happens whether I am logged in or not, and it still occurs when I install it on a fresh vault.

iOS 16.2; Obsidian 1.4.1 (83)

**Comment by YukiGasai** [comment]
Hi,
do you get any error messages in the console when starting obsidian or the plugin?

I don't have a ios device so I can't really debug this myself.

**Comment by joshwent** [comment]
Hi,
Unfortunately there is no way to access the console on iOS as far as I’m aware. I’ll look into this again later today, though, and see if there’s another way I can get log data.

**Comment by YukiGasai** [comment]
Are you testing on macOS (Desktop) if yes, have you tried  `Ctrl` + `Shift` + `i`

**Comment by YukiGasai** [comment]
I borrowed an iPad and was able to reproduce the problem.
Thank you for reporting this.

**Comment by joshwent** [comment]
When testing on macOS (Desktop) I do not get any errors in the console.

Wow, you are quick! Perfect, thank you so much for looking into this!!

**Comment by YukiGasai** [comment]
I used the [obsidian-dev-tools](https://github.com/KjellConnelly/obsidian-dev-tools) to get the console output on the iPad. When I try to activate the plugin, I get this error. 

```err
"Plugin failure: google-calendar" Object {0}
@capacitor://localhost/app.js:1:235205
s@capacitor://localhost/app.js:1:234096
promiseReactionJob@[native code]
```

From the obsidian discord, the main problems could be:
- usage lookbehind regex (Not supported by safari)
- usage of node libraries that don't exist on mobile


I really looked hard and the only thing where I thought the issue could be from, is the module marked used for transforming markdown to HTML. This created a lookbehind regex in the main.js file. But after removing it, the same error occurred.

On the discord someone debugged it like this:
```
Okay, so copy/pasting the entire generated main.js file into Safari's console (on desktop) is a good way to at least get an idea about what's wrong on mobile as Safari is clearly stating what it can't parse.  (Yes, regex.)
```
If you have time to do this, this could be helpful.

**Comment by joshwent** [comment]
When running in Safari on desktop, I get the following error in the Javascript console:

`Not allowed to load local resource: file:///favicon.ico`

**Comment by YukiGasai** [comment]
Did you just the file in the browser, or did you run the code from the file in the terminal itself? I looks like you just tried to open the file in the main window.

**Comment by joshwent** [comment]
Apologies as I'm relatively new to javascript. When I tried running main.js, I get the following error:

```
Error: Cannot find module 'obsidian'
Require stack:
- /Users/USERNAME/working_directory/obsidian/obsidian-google-calendar/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1053:15)
    at Module._load (node:internal/modules/cjs/loader:898:27)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (/Users/USERNAME/working_directory/obsidian/obsidian-google-calendar/main.js:75:42081)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:935:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:84:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/USERNAME/working_directory/obsidian/obsidian-google-calendar/main.js'
  ]
}
```

From a quick google search, it seems that the obsidian module can't be referenced outside of obsidian? Can you confirm this? If so, I'm not sure how I can go about running this outside of Obsidian on desktop

**Comment by YukiGasai** [comment]
Thank you. Perfect, that confirms that there is a bad regular expression in there somewhere.
Is there a line number by any chance?

**Comment by joshwent** [comment]
I can't seem to find a line number unfortunately. That being said, I tried searching for the lookbehind regex in the main.js just as you initially suggested (I found it here `a=/(?<!#.*)`), and when I removed `?<!` then the iOS app was able to load the plugin!

I'll see if I can get it to give me a more useful output with a line number

**Comment by joshwent** [comment]
Awesome, thank you very much!! This plugin has been a godsend for me, so I'm excited to get it running on my phone as well.

I appreciate the support!!

**Comment by YukiGasai** [comment]
I removed the open module and created a new version 1.7.17.
Please update the plugin on your devices and check if it works now. Thank you for your help <3.

If everything works as expected, you can close this issue.

**Comment by joshwent** [comment]
That fixed it! The new version works on iOS :)

Thanks again for responding and fixing this so quickly :)
