### ISSUE TITLE
Schedule Visual Bug - hourRange

### ISSUE THREAD

**Issue by BoxThatBeat** [YukiGasai/obsidian-google-calendar#53]
There is a small visual bug when using the hourRange setting for the schedule view where the first and last hours are not in view.
Example: With hourRange: [7, 17]:
![image](https://user-images.githubusercontent.com/28713093/213932548-fd90c960-cb89-42b5-8301-44273debe1e9.png)

The 7 and 17 hour mark are not visible.

**Comment by YukiGasai** [comment]
This is now contained inside Version 1.8.4 
Thank you
