### ISSUE TITLE
Change Name of notes 

### ISSUE THREAD

**Issue by Nzeedave** [YukiGasai/obsidian-google-calendar#55]
Is there a possibility to change the (default) name of notes. 

My note naming pattern includes the date as well as a prefix to indicate what kind of note it is. 
However, when I apply this to a note created with the plugin from an event, I can't open the event from the note. 
I tried circumventing the problem with creating an alias of the old name but this doesn't work either. 

So far I use templater to rename the file. 
I could see a way to hack a solution with templater (if renamed file exists: delete current file and open renamed file) but this feels really hacky and I'd prefer not to write a template that can delete files. 
Therefore I wanted to ask whether its possible to just change the default filename (In that case the create note / open note also remains intact). 

Thanks!

**Comment by Nzeedave** [comment]
Thank you for the quick reply (and the amazing plugin!)

For my usecase the first approach would work.
However, I think the second solution would be better. This also allows renaming notes (e.g. when the event name had a typo, the creator chose a bad name, the focus of the event shifted) .
Personally, I use a dedicated folder for meeting notes.
As an alternative I could also imagine a filename filter for event notes if someone likes a different folder structure (e.g. all event notes start with m_, or end with _m).

**Comment by Nzeedave** [comment]
Thanks, sounds great! 

And of course the "g_" prefix also works. 
And the backwards compatibility is a good point.

**Comment by YukiGasai** [comment]
Hi @Nzeedave,
I took some time, but I added two options. It would be great if you could also test this a little. I tried around with it and it seemed to work good for me, but there are too many options to cover.
![image](https://user-images.githubusercontent.com/38146192/217874857-7d2d11f4-e296-4a51-8c73-a67ffa3d18f4.png)


As a default, there is no prefix, but you can add it if you see some performance problems.
The default for the event note has the prefix, but if it's empty it is simply ignored.
