### ISSUE TITLE
gEvent Week view

### ISSUE THREAD

**Issue by willtree8** [YukiGasai/obsidian-google-calendar#58]
Hiya, enhancement suggestion/question here. The web and app versions of gcal have 4 day views as well as week views. They are closer to the day view in that they show the entire day in a timeline.
Is it possible to achieve this in this plugin? The month view is great but looses lots of detail compared to the day view which isn't enough data. If not already possible then my proposal would look like multiple of the 'day' view side-by-side to fit the desired number of days.

Thanks!

**Comment by YukiGasai** [comment]
Hi @willtree8, let's add the last missing view ^^

I started working on the `week` code block, but this all could be added to the timeline (day) code block with ease. 
Should this really be a separate code block?

![image](https://user-images.githubusercontent.com/38146192/215912721-aa56cc5f-0ca3-456f-9ec0-e0bb08e0d54e.png)


If you have CSS experience you can maybe help out with the styling, the biggest problem is the minimal space and all the absolute elements.

Example for the codeblock
~~~
```gEvent
type: week
timespan: 5
dayOffset: -2
hourRange: [1, 18]
navigation: true
```
~~~

**Comment by YukiGasai** [comment]
I added the command `Google Calendar: Open week view` and fixed some CSS
