### ISSUE TITLE
Creating Google Event with dateTime doesn't work

### ISSUE THREAD

**Issue by vanbang9710** [YukiGasai/obsidian-google-calendar#59]
When running command "Create Google Calendar Event", I can create All day Event. But nothing happens when clicking "Create" for an event with dateTime
![image](https://user-images.githubusercontent.com/52906188/215353489-b017a879-050d-4507-8007-b0f091f56672.png)

**Comment by YukiGasai** [comment]
Thank @vanbang9710 for bringing up that issue.
I used the wrong formatting for the dateTime.
Please check out the latest version and close the issue if everything works as expected again.

**Comment by vanbang9710** [comment]
This also fixes the same problem with the command Create from frontmatter. I wasted 1h wondering if my dateTime format is right :<
