### ISSUE TITLE
Improvement to "Create Google Calendar Event"

### ISSUE THREAD

**Issue by Gjessing1** [YukiGasai/obsidian-google-calendar#6]
My wishlist for "Create Google Calendar Event"
1) Option to choose default calendar (right now i get multiple options of calendars, but the default is not my google calendar)
2) If start date is set to a future date, change end date to the same date
3) Default time when creating event should be rounded to closest 15. minute mark

Thanks for a promising plugin.

**Comment by YukiGasai** [comment]
Thanks for the input.
I added a new setting to set a default calendar and implemented 2 and 3 in version 1.1.6
Please take a look.

**Comment by Gjessing1** [comment]
Working great, thank you alot!
