### ISSUE TITLE
Can't use the plugin since the last update

### ISSUE THREAD

**Issue by nicosomb** [YukiGasai/obsidian-google-calendar#60]
Hello!

Thank you for your plugin. 
Since the last update (1.8.5), I can't display calendars or events (when i click on "List google events" for example). 

What kind of information can I give to you to help debbuging?

**Comment by YukiGasai** [comment]
Hi @nicosomb,
I was not able to reproduce your issue.
You can log out and login again, just to make sure.
Please turn on the debug option in the settings and open the dev console with `Ctrl` + `Shift` + `i`. 
Clear the console with `Ctrl` + `l` then try you steps again and send me the output inside the console.

**Comment by nicosomb** [comment]
>  You can log out and login again, just to make sure.

Yeah, it works fine. Thank you.
