### ISSUE TITLE
Using the plugin on Mobile ?

### ISSUE THREAD

**Issue by MagiqueID** [YukiGasai/obsidian-google-calendar#65]
Hi,

It is possible to use the plugin on Mobile?
I don't understand the documentation:
"
Login on a desktop device
Use the Copy Google Refresh Token to Clipboard command on that device
"
I can't find the "Google Refresh Token"

Thanks for your help

**Comment by L9MShrn9iSWKjzv4sKRz** [comment]
On desktop, assuming you're on Obsidian in Windows:

Ctrl + P -> Type Google Calendar: Copy Google Calendar Refresh Token to Clipboard

Paste that one into mobile.

**Comment by MagiqueID** [comment]
Ok, thanks!
