### ISSUE TITLE
More options for "Insert Google Events"

### ISSUE THREAD

**Issue by caasion** [YukiGasai/obsidian-google-calendar#67]
Hello, since I've found this plugin, I've fallen in love with how well it has been thought out. This plugin holds more functionality than any other calendar plugin in Obsidian. However, I have a feature request/question about inserting google events.

1. **Question**: Is it possible to fetch events of X day when creating a file from a template? I would like to have all the events of the day ready in my daily note when I create it.

2. **FR**: the option to disable linking to the calendar event for certain events (perhaps configurable in the description of the event).

3. **FR**: the option for an alias of the event when it is inserted (configurable in description). This would be useful if I want to insert more details in Obsidian, but don't want to clutter my calendar. Example:
Actual Event Name: Math Class
Inserted Event Name: Math Class @ 10:00

**Comment by YukiGasai** [comment]
Hi
# Answer 1

The plugin has integration for the core templates plugin and templater.

I can only recommend using templater.

### Option 1:
You can create a template file with {{gEvent.AnyField}} placeholders to insert any event information into a file and then run `Create Event Note`. You can even automate this process With [Auto Create Event Note](https://yukigasai.github.io/obsidian-google-calendar/#/Advanced/AutoCreate).

### Option 2: 
If you have some programming background. You can use the exposed API with templater to insert information of events into a note #13. This option is more flexible IMO.

# Answer 2
I don't understand that idea. If you want to remove calendars from the plugin, you can add them to the blacklist in the settings. 

# Answer 3
I believe this example is achievable with templater as described in Option 2.


Feel free to ask more questions, I know that the documentation is a giant mess and I am happy to help.

**Comment by caasion** [comment]
For the second one, events are hyperlinks when they are inserted:

![image](https://user-images.githubusercontent.com/103465188/218875566-ff0e8779-cf25-4b8c-ace9-d2dbe6f381e6.png)

but this might be annoying if I just want to have it in my daily note, so it would like the option to not include a hyperlink to the calendar event.

**Comment by YukiGasai** [comment]
What template plugin are you using to insert the links?

**Comment by caasion** [comment]
Currently, I haven't tried using a template plugin; I've only used the command `Insert Google Events`.

**Comment by caasion** [comment]
Hi,

I have been trying out the plugin API a bit, but I am having trouble/have questions:

1. How do I get the start time and end time of an event? I want to process that and add it to the text I insert.
1. How do I get the tasks of a specific day (using templater)? This is my current code:

```js
const date = await tp.file.title

const {getEvents} = this.app.plugins.plugins["google-calendar"].api;

const dateMoment = moment(date, "YYYY-MM-DD ddd");

const events = await getEvents(dateMoment);
const eventsString = events.reduce((text, event) => text +=`- ${event.description} \n`, "");

tR = `${eventsString}`
```

For some reason, I still get the events of today even though `dateMoment` is tomorrow.

**Comment by YukiGasai** [comment]
Yea the documentation hits again. #13
> Updating the example:
> 
> ```
> Example:
> <%*
> const {getEvents} = this.app.plugins.plugins["google-calendar"].api;
> const theEvents = await getEvents({
> startDate: window.moment("12/06/2022")
> });
> console.log(theEvents);
> tR = theEvents.reduce((text, event )=> text += "\n" + event.summary,  "");
> %>
> ```
> 
> The argument for the getEvents function is a object now to allow named params
> 
> ```
> {
>     startDate?: moment.Moment;        Querry Start defaults to start of today
>     endDate?: moment.Moment;          Querry End   defaults to end of today
>     singleCalendar?: GoogleCalendar;  A single calendar not realy practical to use in templater
>     exclude?: string[];               A list of names or ids of calendars you want to exclue from the results defaults to empty
>     include?: string[];               A list of names or ids of calendars you want to include in the results  defaults to empty
> }
> ```
> 
> when not using include or exclude, the result will contain all your calendars except the blacklisted ones from the settings page
