### ISSUE TITLE
FR: Quicker way to open daily notes in month view

### ISSUE THREAD

**Issue by caasion** [YukiGasai/obsidian-google-calendar#68]
Hello,

**Rational**: I love that the plugin also takes on the features of the calendar plugin. Unfortunately, the plugin causes more friction in the process of opening daily notes. In the calendar plugin (since it was specifically designed to be for periodic notes), notes open instantly with one click. However, with this plugin, we have to click on the date, then the prompt to open the daily note. 

**Request**: I suggest that with a certain key combination, you can open the daily note directly. For example: 
`shift` + `click` would open it in the current tab
`ctrl` + `right click` would open the note in a new tab
 `left click` would provide options to `open in new tab`, `open to the right`, `open in new window` etc.

**Additional**: `left click` could also allow you to open the schedule view or timeline view of the selected day (and/or week)

**Comment by YukiGasai** [comment]
Hi,
thank you for your inside. I usually don't use the daily notes ^^. 
I will try to add the `shift` and `shift` + `ctrl` option. 
Can you please clarify what the left click should do exactly? Are the new options also in the list of events at that day? If yes, I believe that this would clutter a lot.

**Comment by caasion** [comment]
Hi:
Sorry! I'm not good with left or right and I messed it up. :sweat_smile: The basic idea was that the `right click` would open a small pop-up that gives you option to open the daily note in various ways, something similar to when right clicking a tab:
![image](https://user-images.githubusercontent.com/103465188/218876191-8a7dc4f8-cc62-4a33-b470-0e80aad13eef.png)

Specifically, for the calendar view, it will provide options to `open to the right`, `open in new tab`, and `open in new window`, it basically allows users to have flexibility in opening the daily note even if they don't know the shortcuts.

For the additional request, I once again meant `right click`ing would have options in the pop-up open to `open the schedule view` or `timeline view` of the day you right clicked on 

Sorry for the confusion I have caused :sweat_smile:

**Comment by YukiGasai** [comment]
I added your great ideas in the latest version. 
Added alt to open in new window as well.
If everything works as you expected, you can close this issue.

**Comment by caasion** [comment]
Wow! I love the additions! It was beyond expectations since it opens to the already daily note, making it so there aren't a million of them. 

One minor bug I've found is that the schedule or timeline view opens as a "new tab" in the tab header instead of the "timeline view." So it conflicts with the "Default New Tab Page" plugin because it mistakes it as a new tab.
![image](https://user-images.githubusercontent.com/103465188/219893099-bcda385d-26ef-47ba-8466-7492f026828a.png)

**Comment by YukiGasai** [comment]
Hi @caasion, 
I updated the plugin, so the 2 views will open in their usual location.

**Comment by caasion** [comment]
It works great now! no more conflicts, so I could use the default new tab page plugin in conjunction with this one. thank you for your work!
