### ISSUE TITLE
FR: Open weekly web view

### ISSUE THREAD

**Issue by caasion** [YukiGasai/obsidian-google-calendar#69]
Hello,

It's me again! Three in a row. 

**Rational**: Currently, the web view starts off in day mode. However, there is no timeline view for a week. 

**Request**: a command to open web view in week mode, taking up the main window

**Comment by YukiGasai** [comment]
Hi @caasion,
thank you for you detailed issues.

Is this only concering the gEvent codeblock or do you want this functionality in the obisdian views aswell.

I am thinking about adding setting for switching the default view instead of adding more commands, what do you think.

**Comment by caasion** [comment]
Hello:
I was mainly thinking about the obsidian views because I tend to gravitate towards them more. I think adding a setting to switch the default view would have less clutter with commands; in other words, it is a good idea!

BTW: is there a possibility to open a week's timeline view in an obsidian view? I just found out it was possible with the codeblock, but I'm not sure how to do it with the view.

**Comment by YukiGasai** [comment]
It's not possible currently because the week view is still in progress.

**Comment by YukiGasai** [comment]
You can now change the default web view mode in the settings.
In code blocks, the `view` attribute can overwrite the default.
Options: `day`, `week`, `month`, `agenda`

**Comment by caasion** [comment]
Great work! I love it (and probably so do many others who use this plugin). Keep it up!
