### ISSUE TITLE
google calendar timeline view changing days

### ISSUE THREAD

**Issue by hongdavid94** [YukiGasai/obsidian-google-calendar#70]
I apologize in advance for not providing enough details. I am not sure which information I can provide to help you debug this issue.

I personally won't use the timeline view as I like other view modes, but I want to report that the timeline view buttons are not working properly. Pressing Forward/Back one day/week would not give accurate results. For instance, it would forward 4 days or 2 days instead. It is almost random (sometimes it goes the opposite direction or even changes month).

Has this been reported with others? Thanks

**Comment by caasion** [comment]
I am also experiencing the same issue with timeline view. Sometimes it goes forwards by several days, sometimes it doesn't go forward at all.

This was my experience:
[Screencast from 2023-02-16 16-30-58.webm](https://user-images.githubusercontent.com/103465188/219491563-57462b14-4254-4e47-911f-ec1c4a0e2788.webm)

**Comment by YukiGasai** [comment]
Hi @hongdavid94,
I think I fixed this issue. Please test it yourself and close the issue if everything works as expected.
