### ISSUE TITLE
[FR] Change in where certain views are opened

### ISSUE THREAD

**Issue by caasion** [YukiGasai/obsidian-google-calendar#71]
HI! Me again.

I love the recent addition of the new "week view" and the customization options for the web view. Thank you for listening to us and incorporating our suggestions!

**Request**:
With the addition of these views, it would be great if the `week view`, `week view (for web mode)`, and `month view (for web mode) opened in the main window. This is necessary because they are very cramped on the right sidebar: 
![image](https://user-images.githubusercontent.com/103465188/219895304-4da89b40-907d-483c-9ab2-163a54effa80.png)
, but it looks much better in the main window 
<img src="https://user-images.githubusercontent.com/103465188/219895371-665a1879-756a-47b6-bfa7-8e7d55ab801c.png"  width="750" height="600" />
**Additional**:
This is only somewhat related, but if we open the web week view in the main window, we can see that it is cut off. Is it possible to make it fit the screen?
![image](https://user-images.githubusercontent.com/103465188/219895682-4a8f539e-33a8-4436-9e24-e5032c1debb8.png)

**Comment by YukiGasai** [comment]
I will update the current commands to check if obsidian is running on mobile.
I can't reproduce the main window behavior
![image](https://user-images.githubusercontent.com/38146192/219899239-4ebf32a0-f238-4328-97c0-705b68593cc5.png)

**Comment by YukiGasai** [comment]
Hi @caasion,
the plugin will now check if it is running on mobile and will open the view in the main panel if so.
I also fixed the web view bug.
Please test it yourself and close the issue if everything works as expected ^^

**Comment by caasion** [comment]
I may have caused some confusion with the feature request:

Currently, the week views opens on the right sidebar, which is basically useless because I can't see anything there (when I choose week view):
![image](https://user-images.githubusercontent.com/103465188/219978054-5d8a372c-df7c-4a98-a735-02a399578f6f.png)
![image](https://user-images.githubusercontent.com/103465188/219978056-9b18ac4f-3c1a-439a-abf5-586620df22cc.png)

So the request was for these (weekly and monthly web view, week view) to be opened in the main panel by default.

Please consider this suggestion, thank you. :smile:

**Comment by YukiGasai** [comment]
Ohh I think I just miss read this to be honest, but mobile support can not hurt :) 
The new default position will be added with the new version.

**Comment by caasion** [comment]
I haven't tried using this plugin on mobile, but having that functionality on mobile would help a lot! Thank you for your work as always. :smile:
