### ISSUE TITLE
403 error - please help

### ISSUE THREAD

**Issue by johnsonblue75** [YukiGasai/obsidian-google-calendar#73]
Hi guys, I'm trying to install this - I'm not a programmer - it looks awesome - but I keep getting a 403 error from when I got to login with my gmail account. I believe I followed all your instructions and suspect it's not properly setup as a test account, though I'm not really sure if that it. I'm on Win 11. Thanks.

**Comment by johnsonblue75** [comment]
Here's my actual error at Google Login screen:

Request details: access_type=offline response_type=code redirect_uri=http://127.0.0.1:42813/callback prompt=consent client_id=********MYID**********.apps.googleusercontent.com scope=https://www.googleapis.com/auth/calendar

**Comment by NaturallyAsh** [comment]
@johnsonblue75 This may or may not be the issue for you, but I got the same error and my problem was that I had my VPN up and running. After I disconnected from my VPN, I was able to login.

**Comment by johnsonblue75** [comment]
Hi @NaturallyAsh thanks for your comment. I was able to get this working. I found the developer's more in-depth walk through with screenshots and followed that. Four tries later I got it!

**Comment by YukiGasai** [comment]
Hi,
I added a link to the guide to the README and inside the settings.
