### ISSUE TITLE
[FR] Offline Support for Calendar View

### ISSUE THREAD

**Issue by caasion** [YukiGasai/obsidian-google-calendar#74]
Hi,

I would like to have offline support for the calendar view, so even though I am not connected to the internet, I can still use the calendar view to access my daily notes.

Thank you!

**Comment by YukiGasai** [comment]
Hi @caasion,
I think I made it work. I updated a lot about the event caching to decrease the amount of requests. If you encounter any problems, you can just report them here.

**Comment by caasion** [comment]
Working great so far! Thank you!
