### ISSUE TITLE
i keep getting this error when i try to log in

### ISSUE THREAD

**Issue by nammminn2** [YukiGasai/obsidian-google-calendar#75]
https://share.cleanshot.com/vZ3LRk18

**Comment by YukiGasai** [comment]
Hi @nammminn2 and @caasion,
thank you for bringing this problem up so fast.
With the last update, I broke the setup for the authentication process. I reverted this change.
Please check if the authentication works for you again.

**Comment by SamirAyman10** [comment]
Hi Yuki,

The same goes for me. I tried to log in today but I have the same error.

**Comment by YukiGasai** [comment]
Hi @SamirAyman10, 
I tested the setup again, even with a new client, and can no longer reproduce this problem.
- Have you updated to the latest version (1.8.13) ?
- Are you using your own client ?

**Comment by SamirAyman10** [comment]
@YukiGasai , Should I Use on authentication client to true and follow your instructions? Or should I set it to false and click the login to Google button? (This is the option I was referring to)

**Comment by YukiGasai** [comment]
@SamirAyman10 yes please use own authentication should be set to true. Like in this picture
![image](https://user-images.githubusercontent.com/38146192/222408065-eabe8c0b-8903-4cca-8253-655084f4832c.png)
Then use the setup instructions to create an own client to obtain the client ID and secret.
Then Press the Login button.

The public client is currently full and has to be checked by google to remove the test user limit. Until then, the only option is to create an own client.

**Comment by SamirAyman10** [comment]
@YukiGasai Thank you very much it worked. Much appreciated !

**Comment by nammminn2** [comment]
tysm will try now
