### ISSUE TITLE
[BUG] Discrepency between actual All-day events and ones fetched

### ISSUE THREAD

**Issue by caasion** [YukiGasai/obsidian-google-calendar#76]
Hi,

I found there are discrepancies between all-day events in my calendar and all-day events found in the plugin.
When I do "Insert Google Events", I get "Good Friday" and "Easter Monday" as all-day events.
![image](https://user-images.githubusercontent.com/103465188/222715185-a493d5c0-d667-4b23-8353-2b85100795da.png)
However, on my actual calendar, these only happen in April (and aren't on the same day):
![image](https://user-images.githubusercontent.com/103465188/222715263-d9615e6d-2768-44e6-aa72-baec055ecf8e.png)
Could you please take a look at this issue?

Thank you.

**Comment by YukiGasai** [comment]
Hi, this looks like a timezone problem. Could you tell me your timezone, so I can reproduce this bug?

**Comment by caasion** [comment]
my time zone is EST

also, i've been getting these same events everyday since then, so i'm not sure if it is really related to the timezone

**Comment by YukiGasai** [comment]
I think #88 could be related to this issue.

**Comment by YukiGasai** [comment]
@caasion could you check if this is fixed for you?

**Comment by caasion** [comment]
hi, sorry for the delay, this has been fixed for me. thank you for your work!
