### ISSUE TITLE
Schedule View

### ISSUE THREAD

**Issue by pastorjack** [YukiGasai/obsidian-google-calendar#8]
Hi again!
Thanks for the implementing the schedule view. I've tried to tweak the CSS, but working with 'flex' is over my head. It has been a while since I worked with CSS. I love the current view when I have a wide window, but it is doesn't fit on a narrow window or my phone.
![image](https://user-images.githubusercontent.com/121033/185972019-83b492a5-3b23-42b3-a78b-7415157bdd4a.png)

Would it be possible to make it responsive? or create a separate view that is a simple list, like this
Date (e.g., Mon, Aug 22)
colored dot - time 
Event title (with clickable link to modal)

Thanks for a great plugin!

**Comment by pastorjack** [comment]
Definitely better on narrow windows!!!
![image](https://user-images.githubusercontent.com/121033/187244869-de0f8b89-9ee3-4819-bf31-c1f260e92b52.png)
Thanks!

**Comment by freqyfreqy** [comment]
https://github.com/YukiGasai/obsidian-google-calendar/discussions/87

I'm running into the 'opposite' issue. Can I get this looking more appropriate for 'wider' screens on my desktop? Is there a way to have it look good on desktop(wide screen) and mobile(narrow screen)?
