### ISSUE TITLE
Option to change "Auto create Event Notes" description marker, instead of being fixed to  `:obsidian:`

### ISSUE THREAD

**Issue by marcdus** [YukiGasai/obsidian-google-calendar#81]
It would be very neat if you could specify what the keyword is for auto-creation of event notes. E.g., not just the calendar events containing `:obsidian:` in their description are included, but whichever the user wants.

This should be easily possible by allowing the modification of line 46 in `src/helper/AutoEventNoteCreator.ts`, right?

My use case is that I could then just use google-calendar to fetch all events, and use the created notes for full-calendar, or habit tracking etc. Thanks a lot for you work, it's highly appreciated!

**Comment by YukiGasai** [comment]
Hi @marcdus,
we can try to allow custom string for identifying events to be auto imported.
Do you need the colon to be removed, because this would make it a lot harder, as they function as a limiter for the left and right variables.
If possible, please share your ideal string.

**Comment by marcdus** [comment]
Thank you for your quick response!
I understand. If that is the case, would it be possible to have a dropdown option, e.g. 

_Auto-create note for calendar entries:_
1. _None_
2. _All_
3. _Only notes that contain `:some_string:`_

If the user selects one/two, the note would not need to be searched for a string, right? And if option three is selected, you run the function to identify the desired string. For my use case I would choose option two. What the `:some_string:` is does not matter to me.

Best, Marc

**Comment by YukiGasai** [comment]
Hi, please check if the update is working for you.

I added the option.
![image](https://user-images.githubusercontent.com/38146192/228688510-6d1bf408-f033-438d-a196-77ca4aed7efd.png)
Keeping the field empty will import all notes, turning off Auto Create event notes will disable the import, other input text will be used as marker.
