### ISSUE TITLE
Inserting events suddenly defaulting to display all the events within a month when current date is selected

### ISSUE THREAD

**Issue by novakwh** [YukiGasai/obsidian-google-calendar#88]
Hi, I always use the insert events option to stick each day's events into my daily note; lately when I do this, it defaults to showing most of the events within a given month on the current date (checkboxes checked), instead of just the events for that specific date. If I change the date to a different date, it shows only the events for that specific date; but as long as the date is set to the current date (this happens every day for at least the last week), it lists most of the events for the month, including those on different dates, and most (but not all) of them are checked off to insert. It's extremely strange and definitely wasn't doing this before.

**Comment by novakwh** [comment]
Ah I had logged out, logged in, and restarted, and none of that seemed to help -- but I guess I had forgotten to just disable and then re-enable the plugin; I just did so, and now it seems to be working again.

**Comment by novakwh** [comment]
And whoops, it happened again. The issue seems to have something to do with having the Google Monthly Calendar view open -- I like to keep this open in my sidebar. But when it is open, I get that weird bug with all the events for the month showing up in the insert events for current date. Close the monthly view, and insert events works fine.

**Comment by YukiGasai** [comment]
Hi @novakwh,
thank you for bringing this issue up. I was able to reproduce this and it looks like a problem with the caching implemented in 724fd1c. I will work on it.
