### ISSUE TITLE
Can't list any calendars

### ISSUE THREAD

**Issue by howesteve** [YukiGasai/obsidian-google-calendar#89]
Hello.

Thanks for this project and effort put on it. However, I can't use the plugin. I'm logged but can't list or access any calendars.

1) I'm made my own Google OAuth client.
2) Google OAuth reports:
```Authentication successful! Please return to obsidian```
![image](https://user-images.githubusercontent.com/3008471/226149484-ef5c9e86-161f-4744-a6d9-a56cd181251e.png)
3) I'm logged into the plugin:
![image](https://user-images.githubusercontent.com/3008471/226149512-c693cd1c-ede4-47cb-8bcc-daf1756ac980.png)
4) Calendar web view works, but not any other views:
![image](https://user-images.githubusercontent.com/3008471/226149635-c014de0d-5092-4885-9e3f-31f26c7105b6.png)
5) And no calendars can be listed:
![image](https://user-images.githubusercontent.com/3008471/226149573-e36b4c94-fbc2-405d-99fe-7ec9800c7d1e.png)
6) Developer console reports an error, but it didn't help a lot.
![image](https://user-images.githubusercontent.com/3008471/226149823-31fecfef-cfc0-4cf9-b76e-f182bfffb232.png)
7) I'm using the latest version of the plugin as of now, and did try logging in and out several times.  I'm trying to use this plugin for a couple of weeks, I've upgraded it several times in hope a new version could fix it, but the situation is always as above.

I have no idea what can be wrong. Any hints?

Thanks.

**Comment by YukiGasai** [comment]
Please enable the debug Mode in the settings and check the console output and networking tab again for more detailed errors.

**Comment by howesteve** [comment]
It appears I had failed to grant a permission to use the google calendar api in the google console panel. After that and some reboots, it's working now.
I believe an actual error message without setting debug mode would have been be helpful, even if just said "turn on debug mode to find out".

Thanks
