### ISSUE TITLE
[Bug] Test template doesn't exit

### ISSUE THREAD

**Issue by rapatel0** [YukiGasai/obsidian-google-calendar#9]
Awesome plugin man. 

Running the reference template text, i get the errot "Reference template doesn not exit" Any ideas?

```
Event Organizer

<%gEvent.organizer.email%>

```

**Comment by YukiGasai** [comment]
Hi, thank you for testing.
Templater doesn't really allow custom template strings. I changed the code a little, please try this with the new version. 

```
Event Organizer

{{gEvent.organizer.email}}
```

**Comment by rapatel0** [comment]
Didn't work. Says the template doesn't exist and then say it's incompatible. 

<img width="1525" alt="image" src="https://user-images.githubusercontent.com/18704704/188320744-31db8bb5-df3f-4d79-8fb9-b91c5420c73c.png">

**Comment by YukiGasai** [comment]
Thank you for testing the plugin.

There was a problem with templates in the root folder.
Check out version 1.2.4
If it still doesn't work, please answer the following questions for debugging.

- Is templater enabled?
- Is the core template plugin additionally enabled?
- What are the set template folders in the settings?
- Are there any errors in the console?

**Comment by rapatel0** [comment]
Still not working

> Is templater enabled?
Yeah it is. 

> Is the core template plugin additionally enabled?
 No it is not

What are the set template folders in the settings?
For templater it's:
`/Utilities/Templater/Notes`

I don't see one specifically for Obsidian-Google-Calendar
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/18704704/188461774-ba24192b-8842-4c09-a9a5-400c1528f37e.png">


Are there any errors in the console?

A few but not sure they are relavent
<img width="516" alt="image" src="https://user-images.githubusercontent.com/18704704/188462024-4c3c2157-9c94-4b11-9d59-c722676f1f00.png">

**Comment by YukiGasai** [comment]
Please make sure the template you want to use is inside the template folder.

**Comment by rapatel0** [comment]
Tried it. Still doesn't work

**Comment by rapatel0** [comment]
Nevermind. I figured it out. 

- The template only works if its exactly in the template folder (not a sub folder within the template folder)

**Comment by rapatel0** [comment]
Note this plugin breaks with
- filename heading sync
- default new tab page

**Comment by YukiGasai** [comment]
Please check, but I think subfolders are already possible.
When using a folder, just use the complete path to the template from the selected template folder as start like this.

`:subTemplate/TemplateFile-obsidian:`

**Comment by rapatel0** [comment]
Cool. I assumed that the code would recursively traverse all subfolders to look for the template file. I didn't try using the template with the explicit path

**Comment by YukiGasai** [comment]
> Still figureing out how to use this plugin as it breaks a lot of my templater based workflow. Thanks

What kinds of workflows does the plugin beak. Can you give an example?

**Comment by rapatel0** [comment]
This might be worth moving to a discussion forum, but here is an example 

for every meeting, I link the attendees using backlinks in my personal Obsidian CRM. Example: [[Attendee1]], [[Attendee2]]...

I cannot really do that with the templateing finction. 

I also use templater with a suggester modal to dynamically link projcects when I create a meeting note. 

Both of these usecases require some
- User interaction at template creatiion time, 
- Postprocessing of information. 

It would be incredible to have an api that is exposed to tempater and dataview. That would make existing workflows much easier to use

**Comment by YukiGasai** [comment]
I check a bit and found the following
- [Templater Issue](https://github.com/SilentVoid13/Templater/issues/839)

It looks like this syntax could work [MetaEdit](https://github.com/chhoumann/MetaEdit#new-task-template-requires-templater).

I will check and see what I can do to expose an API, but let's close this issue for now.
