### ISSUE TITLE
After update to 1.8.17 settings disappears 

### ISSUE THREAD

**Issue by P4cster** [YukiGasai/obsidian-google-calendar#94]
After updating to 1.8.17 I see the installed plugin in the community plugins but the settings disappeared as well as the whole functionality. No commands, no views whatsoever just as it isn't installed. Downloaded the zip as well and installed manually. Obsidian Version stable 1.1.16 (installer 1.0.3)

Regards

Edit: downgraded to 1.8.16. works like a charme

**Comment by YukiGasai** [comment]
Hi @P4cster,
I tried to reproduce this, but in my own and a new vault, I was not able to get the same result when updating or installing the plugin. Could the plugin be disabled after the update?

What OS are you using and could you test it with an empty vault as well?

**Comment by P4cster** [comment]
Updating to 1.9 fixed it. Perfect, thanks. Obsidian Version 1.2.1 Insider (installer 1.0.3). Great plugin btw. Couldn't live without it.
