### ISSUE TITLE
Link note to event

### ISSUE THREAD

**Issue by imeed166** [YukiGasai/obsidian-google-calendar#96]
I tried using the API with templater plugin to create, update, delete events whenever the note was created, updated or deleted. But I encountered a problem, whenever I was offline, or I was on my phone (obsidian too slow to load) I couldn't use the plugin API.

So I thought, maybe it should be a feature built into the plugin itself. My vision for implementation would be to periodically check for notes that contain a specific keyword or phrase in their frontmatter.  This way, even if there was no wifi or the note was added from outside of Obsidian, the plugin would automatically link it afterwards. 
Of course, we would provide the necessary information for it to work, for example :
```YAML
googleCalendarLink: true 
start: YYYY-MM-DD 
end: YYYY-MM-DD 
```

This is just a proposition, if it's too difficult to implement, I can search for another way. Thanks again for the plugin.

**Comment by YukiGasai** [comment]
Hi, I know this is not exactly what you want, but please check out the command `Create Google Calendar Event from Frontmatter` for the usage check out #30 and #34

**Comment by YukiGasai** [comment]
Closed due to inactivity.
